# **2. DATA UNDERSTANDING**

## **LIBRARIES**

In [ ]:
! pip install adlfs azure-storage-blob

Collecting adlfs
  Downloading adlfs-2024.12.0-py3-none-any.whl.metadata (7.7 kB)
Collecting azure-storage-blob
  Downloading azure_storage_blob-12.26.0-py3-none-any.whl.metadata (26 kB)
Collecting azure-core<2.0.0,>=1.28.0 (from adlfs)
  Downloading azure_core-1.35.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 1.9 MB/s eta 0:00:00
Collecting azure-datalake-store<0.1,>=0.0.53 (from adlfs)
  Downloading azure_datalake_store-0.0.53-py2.py3-none-any.whl.metadata (19 kB)
Collecting azure-identity (from adlfs)
  Downloading azure_identity-1.24.0-py3-none-any.whl.metadata (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 4.1 MB/s eta 0:00:00
Requirement already satisfied: fsspec>=2023.12.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (2025.3.0)
Requirement already satisfied: aiohttp>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (3.12.15)
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (43.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (4.14.1)
Collecting isodate>=0.6.1 (from azure-storage-blob)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.20.1)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (2.32.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (1.17.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.17.1)
Collecting msal<2,>=1.16.0 (from azure-datalake-store<0.1,>=0.0.53->adlfs)
  Downloading msal-1.33.0-py3-none-any.whl.metadata (11 kB)
Collecting msal-extensions>=1.2.0 (from azure-identity->adlfs)
  Downloading msal_extensions-1.3.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.22)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from PyJWT[crypto]<3,>=1.0.0->msal<2,>=1.16.0->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.10.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2025.8.3)
Downloading adlfs-2024.12.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 2.9 MB/s eta 0:00:00
Downloading azure_storage_blob-12.26.0-py3-none-any.whl (412 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.9/412.9 kB 16.7 MB/s eta 0:00:00
Downloading azure_core-1.35.0-py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 kB 17.9 MB/s eta 0:00:00
Downloading azure_datalake_store-0.0.53-py2.py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 4.2 MB/s eta 0:00:00
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Downloading azure_identity-1.24.0-py3-none-any.whl (187 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.9/187.9 kB 16.0 MB/s eta 0:00:00
Downloading msal-1.33.0-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.9/116.9 kB 10.1 MB/s eta 0:00:00
Downloading msal_extensions-1.3.1-py3-none-any.whl (20 kB)
Installing collected packages: isodate, azure-core, azure-storage-blob, msal, msal-extensions, azure-datalake-store, azure-identity, adlfs
Successfully installed adlfs-2024.12.0 azure-core-1.35.0 azure-datalake-store-0.0.53 azure-identity-1.24.0 azure-storage-blob-12.26.0 isodate-0.7.2 msal-1.33.0 msal-extensions-1.3.1

In [ ]:
! pip install folium

Requirement already satisfied: folium in /usr/local/lib/python3.11/dist-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.11/dist-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from folium) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.11/dist-packages (from folium) (2025.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (2025.8.3)

In [ ]:
# Standard Library
import os
import io

# DATA MANIPULATION AND ANALYSIS
import pandas as pd
import numpy as np

# DATA VISUALISATION
import matplotlib.pyplot as plt
import seaborn as sns

# AZURE CLOUD STORAGE
from adlfs import AzureBlobFileSystem
from azure.storage.blob import BlobServiceClient
from io import BytesIO

# Geographical map
import folium

# Regular expressions
import re

In [ ]:
# Correctly set pandas display option for max columns and rows
pd.options.display.max_columns = None
pd.options.display.max_rows = None

## **EXTRACT FROM AZURE BLOB STORAGE**

In [ ]:
# Configuration
AZURE_STORAGE_ACCOUNT = os.environ.get("AZURE_STORAGE_ACCOUNT", "researchprojectx24104515")
AZURE_STORAGE_KEY = os.environ.get("AZURE_STORAGE_KEY", "bxpexO6i+Hz6n1WiipTn+sTCuLPGMS1BogMERrIrHd16DpQ0GLfQ0R33yrSw4MxsDomq5yNMgw1o+AStlx/MjA==")
CONTAINER_NAME = "counter-locations"

# Establish connection
connection_string = f"DefaultEndpointsProtocol=https;AccountName={AZURE_STORAGE_ACCOUNT};AccountKey={AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net"
blob_service_client = BlobServiceClient.from_connection_string(connection_string)
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

fs = AzureBlobFileSystem(
    account_name=AZURE_STORAGE_ACCOUNT,
    account_key=AZURE_STORAGE_KEY
)

# Load CSV from Blob
def load_csv(container_client, blob_name):
    blob_client = container_client.get_blob_client(blob_name)
    with BytesIO() as input_blob:
        blob_client.download_blob().download_to_stream(input_blob)
        input_blob.seek(0)
        df = pd.read_csv(input_blob)
    return df

# Load file
counters = load_csv(container_client, "counter_locations.csv")

## **EXPLORATORY DATA ANALYSIS**

In [ ]:
counters.describe()

              _id   Latitude  Longitude
count  131.000000  86.000000  86.000000
mean    66.000000  53.333783  -5.562965
std     37.960506   0.031422   6.427245
min      1.000000  53.250970  -6.422330
25%     33.500000  53.315535  -6.264362
50%     66.000000  53.344060  -6.258875
75%     98.500000  53.348782  -6.240983
max    131.000000  53.409854  53.344410

In [ ]:
counters.head()

,_id,Bike Counter Locations,Latitude,Longitude,Setup Date,User Type
0,1,Aston Quay/Fitzgeralds,53.34668,-6.25988,2019-02-27T00:00:00,Pedestrians
1,2,Bachelors walk/Bachelors way,53.34744,-6.26010,2019-02-27T00:00:00,Pedestrians
2,3,Baggot st lower/Wilton tce inbound,53.33454,-6.24562,2020-08-27T00:00:00,Pedestrians
3,4,Baggot st upper/Mespil rd/Bank,53.33377,-6.24451,2020-08-27T00:00:00,Pedestrians
4,5,Capel st/Mary street,53.34853,-6.26880,2011-08-01T00:00:00,Pedestrians

In [ ]:
counters = counters.dropna(subset=["Latitude", "Longitude", "User Type"])
counters = counters[["Bike Counter Locations", "Latitude", "Longitude", "User Type"]]
counters

,Bike Counter Locations,Latitude,Longitude,User Type
0,Aston Quay/Fitzgeralds,53.346680,-6.259880,Pedestrians
1,Bachelors walk/Bachelors way,53.347440,-6.260100,Pedestrians
2,Baggot st lower/Wilton tce inbound,53.334540,-6.245620,Pedestrians
3,Baggot st upper/Mespil rd/Bank,53.333770,-6.244510,Pedestrians
4,Capel st/Mary street,53.348530,-6.268800,Pedestrians
5,Castleknock Totem,53.370000,-6.349436,Cyclists
6,Charleville Mall,53.356950,-6.245480,Cyclists
7,Clonskeagh Totem,53.306376,-6.237057,Cyclists
8,Clontarf - James Larkin Rd,53.368540,-6.170320,Cyclists
9,Clontarf - Pebble Beach Carpark,53.358250,-6.191070,Cyclists
10,Coast Road Totem,53.388442,-6.124308,Cyclists
11,College Green bike loop @Bank of Ireland,53.345400,-6.259220,Cyclists
12,College Green/Bank Of Ireland,53.345340,-6.259240,Pedestrians
13,College Green/Church Lane,53.344410,53.344410,Pedestrians
14,College st/Westmoreland st,53.345060,-6.258880,Pedestrians
15,Corkagh Park Location 1 - N7,53.305930,-6.412300,Pedestrians/Cyclists
16,Corkagh Park Location 2 - Grange Castle,53.309960,-6.422330,Pedestrians/Cyclists
17,Corkagh Park Location 3 - Cherrywood,53.315520,-6.414770,Pedestrians/Cyclists
18,Corkagh Park Location 4 - Main Car Park,53.315430,-6.410300,Pedestrians/Cyclists
19,Corkagh Park Location 5 - Main Car Park,53.315580,-6.409530,Pedestrians/Cyclists
20,Corkagh Park Location 6 - Fonthill,53.317170,-6.410560,Pedestrians/Cyclists
21,D'olier st/Burgh Quay,53.346840,-6.258870,Pedestrians
22,Dame Street/Londis,53.344470,-6.261520,Pedestrians
23,Dawson Street,53.341194,-6.258337,Pedestrians
24,Dawson Street old,53.342176,-6.258023,Pedestrians
25,Dawson Street/Molesworth,53.341430,-6.258050,Pedestrians
26,Dodder Valley Park 1,53.282210,-6.343920,Pedestrians/Cyclists
27,Dodder Valley Park 2,53.281980,-6.347730,Pedestrians/Cyclists
28,Dodder Valley Park 3,53.278990,-6.356460,Pedestrians/Cyclists
29,Drumcondra Cyclists Inbound,53.363670,-6.257430,Pedestrians/Cyclists
30,Drumcondra Cyclists Outbound,53.362430,-6.258460,Cyclists
31,Dun Laoghaire @ Peoples Park,53.291780,-6.128860,Pedestrians/Cyclists
32,Dun Laoghaire @ Seapoint Beach,53.297320,-6.160740,Pedestrians/Cyclists
33,Dun Laoghaire @ York Road,53.296080,-6.142580,Pedestrians/Cyclists
34,Glenageary,53.281410,-6.123190,Pedestrians/Cyclists
35,Grafton st/Monsoon,53.340770,-6.260580,Pedestrians
36,Grafton Street / Nassau Street / Suffolk Street,53.343550,-6.259320,Pedestrians
37,Grafton Street/CompuB,53.343710,-6.259960,Pedestrians
38,Grand Canal Cycle Path - Lock C5,53.331830,-6.254690,Pedestrians/Cyclists
39,Grand Canal st upp/Clanwilliam place,53.338480,-6.237940,Pedestrians
40,Grand Canal st upp/Clanwilliam place/Google,53.338550,-6.238980,Pedestrians
41,Grange Road Totem,53.286479,-6.277641,Cyclists
42,Griffith Avenue (Clare Rd Side),53.376570,-6.253620,Cyclists
43,Griffith Avenue (Lane Side),53.376550,-6.254670,Cyclists
44,Grove Road Totem,53.329644,-6.270178,Cyclists
45,Guild Street,53.348150,-6.240980,Cyclists
46,Henry Street outside Dunnes Stores,53.329644,-6.270178,Pedestrians
47,Henry Street/Coles Lane/Dunnes,53.348760,-6.262860,Pedestrians
48,Liffey st/Halfpenny Bridge,53.346820,-6.263330,Pedestrians
49,Liffey Street old,53.346725,-6.263270,Pedestrians
50,Mary st/Jervis st,53.348650,-6.266850,Pedestrians
51,Morton Stadium Swords,53.401253,-6.243014,Pedestrians
52,N11 Outbound (Montrose),53.306730,-6.212780,Pedestrians
53,N11 Totem Inbound,53.307094,-6.213874,Pedestrians
54,Newcomen Bridge/Charleville mall inbound (Remo...,53.356450,-6.244180,Pedestrians
55,Newcomen Bridge/Charleville mall outbound (Rem...,53.356480,-6.244180,Pedestrians
56,North Strand Rd N/B (Counter Removed for Roadw...,53.358520,-6.241270,Cyclists
57,North Strand Rd S/B (Counter Removed for Roadw...,53.358600,-6.241120,Cyclists
58,North Wall Quay/Samuel Beckett bridge East,53.347460,-6.240990,Pedestrians
59,North Wall Quay/Samuel Beckett bridge West,53.347500,-6.241400,Pedestrians
60,O'Connell St/Parnell St/AIB,53.352510,-6.261780,Pedestrians
61,O'Connell St/Pennys,53.348790,-6.259690,Pedestrians
62,O'Connell st/Princes st North,53.348950,-6.260040,Pedestrians
63,O'Connell Street Pennys - PYRO EVO Temporary C...,53.346935,-6.259110,Pedestrians
64,Phibsborough Rd/Enniskerry Road,53.363540,-6.272080,Pedestrians
65,Phibsborough Rd/Munster St (Removed due to Ove...,53.363220,-6.272470,Pedestrians
66,Portmarnock Greenway,53.409854,-6.136893,Pedestrians/Cyclists
67,Richmond st south/Portabello Harbour inbound,53.330420,-6.264480,Pedestrians
68,Richmond st south/Portabello Harbour outbound,53.330330,-6.264250,Pedestrians
69,Richmond Street Inbound,53.332160,-6.264400,Cyclists
70,Richmond Street Outbound,53.332160,-6.264400,Cyclists
71,Rock Road Bus Lane,53.308690,-6.195510,Cyclists
72,Rock Road Park - Ped's & Cyclists,53.308770,-6.195630,Pedestrians/Cyclists
73,Rock Road Totem Inbound,53.308120,-6.195030,Cyclists
74,Round Tower Entrance,53.322473,-6.395453,Pedestrians
75,Round Tower Upstairs,53.322361,-6.395447,Pedestrians
76,Talbot st/Guineys,53.350820,-6.255400,Pedestrians
77,Talbot st/Murrays Pharmacy,53.350535,-6.253992,Pedestrians
78,Westmoreland EAST old,53.346045,-6.258960,Pedestrians
79,Westmoreland Street East/Fleet street (Removed...,53.345310,-6.259330,Pedestrians
80,Westmoreland Street West/Carrolls,53.346480,-6.259180,Pedestrians
81,Westmoreland WEST old,53.346034,-6.259275,Pedestrians
82,Wyattville Rd - Bicycles From N11,53.250970,-6.132980,Cyclists
83,Wyattville Rd - Bicycles Towards N11,53.251040,-6.132450,Pedestrians/Cyclists
84,Wyattville Rd At Park Gates,53.251410,-6.132950,Pedestrians/Cyclists
85,Wyattville Road At Steps (Decommissioned Coun,53.251143,-6.132456,Pedestrians

In [ ]:
def normalize_name(name):
    name = name.lower()                       # Lower case
    name = re.sub(r"[^a-z0-9 ]", " ", name)  # Replace any character to space
    name = re.sub(r"\s+", " ", name)         # Replace multiple space to only one
    return name.strip()

counters["Bike Counter Locations"] =  counters["Bike Counter Locations"].apply(normalize_name)
counters

,Bike Counter Locations,Latitude,Longitude,User Type
0,aston quay fitzgeralds,53.346680,-6.259880,Pedestrians
1,bachelors walk bachelors way,53.347440,-6.260100,Pedestrians
2,baggot st lower wilton tce inbound,53.334540,-6.245620,Pedestrians
3,baggot st upper mespil rd bank,53.333770,-6.244510,Pedestrians
4,capel st mary street,53.348530,-6.268800,Pedestrians
5,castleknock totem,53.370000,-6.349436,Cyclists
6,charleville mall,53.356950,-6.245480,Cyclists
7,clonskeagh totem,53.306376,-6.237057,Cyclists
8,clontarf james larkin rd,53.368540,-6.170320,Cyclists
9,clontarf pebble beach carpark,53.358250,-6.191070,Cyclists
10,coast road totem,53.388442,-6.124308,Cyclists
11,college green bike loop bank of ireland,53.345400,-6.259220,Cyclists
12,college green bank of ireland,53.345340,-6.259240,Pedestrians
13,college green church lane,53.344410,53.344410,Pedestrians
14,college st westmoreland st,53.345060,-6.258880,Pedestrians
15,corkagh park location 1 n7,53.305930,-6.412300,Pedestrians/Cyclists
16,corkagh park location 2 grange castle,53.309960,-6.422330,Pedestrians/Cyclists
17,corkagh park location 3 cherrywood,53.315520,-6.414770,Pedestrians/Cyclists
18,corkagh park location 4 main car park,53.315430,-6.410300,Pedestrians/Cyclists
19,corkagh park location 5 main car park,53.315580,-6.409530,Pedestrians/Cyclists
20,corkagh park location 6 fonthill,53.317170,-6.410560,Pedestrians/Cyclists
21,d olier st burgh quay,53.346840,-6.258870,Pedestrians
22,dame street londis,53.344470,-6.261520,Pedestrians
23,dawson street,53.341194,-6.258337,Pedestrians
24,dawson street old,53.342176,-6.258023,Pedestrians
25,dawson street molesworth,53.341430,-6.258050,Pedestrians
26,dodder valley park 1,53.282210,-6.343920,Pedestrians/Cyclists
27,dodder valley park 2,53.281980,-6.347730,Pedestrians/Cyclists
28,dodder valley park 3,53.278990,-6.356460,Pedestrians/Cyclists
29,drumcondra cyclists inbound,53.363670,-6.257430,Pedestrians/Cyclists
30,drumcondra cyclists outbound,53.362430,-6.258460,Cyclists
31,dun laoghaire peoples park,53.291780,-6.128860,Pedestrians/Cyclists
32,dun laoghaire seapoint beach,53.297320,-6.160740,Pedestrians/Cyclists
33,dun laoghaire york road,53.296080,-6.142580,Pedestrians/Cyclists
34,glenageary,53.281410,-6.123190,Pedestrians/Cyclists
35,grafton st monsoon,53.340770,-6.260580,Pedestrians
36,grafton street nassau street suffolk street,53.343550,-6.259320,Pedestrians
37,grafton street compub,53.343710,-6.259960,Pedestrians
38,grand canal cycle path lock c5,53.331830,-6.254690,Pedestrians/Cyclists
39,grand canal st upp clanwilliam place,53.338480,-6.237940,Pedestrians
40,grand canal st upp clanwilliam place google,53.338550,-6.238980,Pedestrians
41,grange road totem,53.286479,-6.277641,Cyclists
42,griffith avenue clare rd side,53.376570,-6.253620,Cyclists
43,griffith avenue lane side,53.376550,-6.254670,Cyclists
44,grove road totem,53.329644,-6.270178,Cyclists
45,guild street,53.348150,-6.240980,Cyclists
46,henry street outside dunnes stores,53.329644,-6.270178,Pedestrians
47,henry street coles lane dunnes,53.348760,-6.262860,Pedestrians
48,liffey st halfpenny bridge,53.346820,-6.263330,Pedestrians
49,liffey street old,53.346725,-6.263270,Pedestrians
50,mary st jervis st,53.348650,-6.266850,Pedestrians
51,morton stadium swords,53.401253,-6.243014,Pedestrians
52,n11 outbound montrose,53.306730,-6.212780,Pedestrians
53,n11 totem inbound,53.307094,-6.213874,Pedestrians
54,newcomen bridge charleville mall inbound remov...,53.356450,-6.244180,Pedestrians
55,newcomen bridge charleville mall outbound remo...,53.356480,-6.244180,Pedestrians
56,north strand rd n b counter removed for roadworks,53.358520,-6.241270,Cyclists
57,north strand rd s b counter removed for roadworks,53.358600,-6.241120,Cyclists
58,north wall quay samuel beckett bridge east,53.347460,-6.240990,Pedestrians
59,north wall quay samuel beckett bridge west,53.347500,-6.241400,Pedestrians
60,o connell st parnell st aib,53.352510,-6.261780,Pedestrians
61,o connell st pennys,53.348790,-6.259690,Pedestrians
62,o connell st princes st north,53.348950,-6.260040,Pedestrians
63,o connell street pennys pyro evo temporary cou...,53.346935,-6.259110,Pedestrians
64,phibsborough rd enniskerry road,53.363540,-6.272080,Pedestrians
65,phibsborough rd munster st removed due to over...,53.363220,-6.272470,Pedestrians
66,portmarnock greenway,53.409854,-6.136893,Pedestrians/Cyclists
67,richmond st south portabello harbour inbound,53.330420,-6.264480,Pedestrians
68,richmond st south portabello harbour outbound,53.330330,-6.264250,Pedestrians
69,richmond street inbound,53.332160,-6.264400,Cyclists
70,richmond street outbound,53.332160,-6.264400,Cyclists
71,rock road bus lane,53.308690,-6.195510,Cyclists
72,rock road park ped s cyclists,53.308770,-6.195630,Pedestrians/Cyclists
73,rock road totem inbound,53.308120,-6.195030,Cyclists
74,round tower entrance,53.322473,-6.395453,Pedestrians
75,round tower upstairs,53.322361,-6.395447,Pedestrians
76,talbot st guineys,53.350820,-6.255400,Pedestrians
77,talbot st murrays pharmacy,53.350535,-6.253992,Pedestrians
78,westmoreland east old,53.346045,-6.258960,Pedestrians
79,westmoreland street east fleet street removed ...,53.345310,-6.259330,Pedestrians
80,westmoreland street west carrolls,53.346480,-6.259180,Pedestrians
81,westmoreland west old,53.346034,-6.259275,Pedestrians
82,wyattville rd bicycles from n11,53.250970,-6.132980,Cyclists
83,wyattville rd bicycles towards n11,53.251040,-6.132450,Pedestrians/Cyclists
84,wyattville rd at park gates,53.251410,-6.132950,Pedestrians/Cyclists
85,wyattville road at steps decommissioned coun,53.251143,-6.132456,Pedestrians

In [ ]:
def map_user_type(x):
    if "Pedestrians" in x and "Cyclists" in x:
        return "FTF_CYC"
    elif "Pedestrians" in x:
        return "FTF"
    elif "Cyclists" in x:
        return "CYC"
    else:
        return x

counters["User Type"] = counters["User Type"].apply(map_user_type)

In [ ]:
# Dublin city centre map
dublin_center = [53.34, -6.26]
dmap = folium.Map(location=dublin_center, zoom_start=12, width=1800, height=800)

# Add markers to map
for _, row in counters.iterrows():
    icon_color = (
        "blue" if row["User Type"] == "CYC"
        else "purple" if row["User Type"] == "FTF_CYC"
        else "green"
    )

    popup = folium.Popup(row["Bike Counter Locations"], max_width=200)

    folium.Marker(
        location=[row["Latitude"], row["Longitude"]],
        popup=popup,
        tooltip=row["User Type"],
        icon=folium.Icon(color=icon_color)
    ).add_to(dmap)

dmap

## **COMPARE TO PREPROCESSED LOCATIONS**

In [ ]:
def load_csv_from_blob(blob_name):
    blob_client = container_client.get_blob_client(blob_name)
    stream = blob_client.download_blob()
    data_bytes = stream.readall()
    data_str = data_bytes.decode("utf-8")
    return pd.read_csv(io.StringIO(data_str))


# Connection configuration
AZURE_STORAGE_ACCOUNT = "researchprojectx24104515"
AZURE_STORAGE_KEY = "bxpexO6i+Hz6n1WiipTn+sTCuLPGMS1BogMERrIrHd16DpQ0GLfQ0R33yrSw4MxsDomq5yNMgw1o+AStlx/MjA=="
connection_string = f"DefaultEndpointsProtocol=https;AccountName={AZURE_STORAGE_ACCOUNT};AccountKey={AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net"
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

fs = AzureBlobFileSystem(
    account_name=AZURE_STORAGE_ACCOUNT,
    account_key=AZURE_STORAGE_KEY
)


# Establish connection to preprocessed dataset
CONTAINER_NAME = "preprocessed"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "preprocessed.csv"
data = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {data.shape}")

Loaded 'preprocessed.csv' with shape: (53424, 56)

In [ ]:
# Extract cycle and footfall targets
cycle_t = [col for col in data.columns if col.startswith("CYC_")]
footfall_t = [col for col in data.columns if col.startswith("FTF_")]
targets = cycle_t + footfall_t

In [ ]:
targets

['CYC_Clontarf James Larkin Rd',
 'CYC_Clontarf Pebble Beach Carpark',
 'CYC_Grove Road Totem',
 'CYC_North Strand Rd N B',
 'CYC_Richmond Street Cyclists 1 Merged',
 'CYC_Richmond Street Cyclists 2 Merged',
 'FTF_Aston Quay Merged',
 'FTF_Bachelors Walk Merged',
 'FTF_Baggot St Upper Mespil Rd Bank',
 'FTF_Baggot St Lower Merged',
 'FTF_Capel St Mary St Merged',
 'FTF_College St Dame St Merged',
 'FTF_Dame St Merged',
 'FTF_Dawson St Merged',
 'FTF_Dolier St Burgh Quay Merged',
 'FTF_Grafton St Monsoon Merged',
 'FTF_Grafton St Nassau St Suffolk St',
 'FTF_Grand Canal St Upper Clanwilliam Place Google Merged',
 'FTF_Henry St Merged',
 'FTF_Mary St Merged',
 'FTF_North Wall Quay Samuel Beckett Bridge East',
 'FTF_North Wall Quay Samuel Beckett Bridge West',
 'FTF_Oconnell St Princes St North Merged',
 'FTF_Oconnell St Pennys Merged',
 'FTF_Phibsborough Rd Enniskerry Road',
 'FTF_Richmond St South Portabello Harbour Inbound',
 'FTF_Richmond St South Portabello Harbour Outbound',
 'FTF_Talbot St Guineys Merged',
 'FTF_Talbot St Murrays Pharmacy Merged',
 'FTF_Westmoreland St East Fleet St Merged',
 'FTF_Westmoreland St West Merged']

In [ ]:
counters = counters.sort_values(by=["User Type", "Bike Counter Locations"]).reset_index(drop=True)
counters

,Bike Counter Locations,Latitude,Longitude,User Type
0,castleknock totem,53.370000,-6.349436,CYC
1,charleville mall,53.356950,-6.245480,CYC
2,clonskeagh totem,53.306376,-6.237057,CYC
3,clontarf james larkin rd,53.368540,-6.170320,CYC
4,clontarf pebble beach carpark,53.358250,-6.191070,CYC
5,coast road totem,53.388442,-6.124308,CYC
6,college green bike loop bank of ireland,53.345400,-6.259220,CYC
7,drumcondra cyclists outbound,53.362430,-6.258460,CYC
8,grange road totem,53.286479,-6.277641,CYC
9,griffith avenue clare rd side,53.376570,-6.253620,CYC
10,griffith avenue lane side,53.376550,-6.254670,CYC
11,grove road totem,53.329644,-6.270178,CYC
12,guild street,53.348150,-6.240980,CYC
13,north strand rd n b counter removed for roadworks,53.358520,-6.241270,CYC
14,north strand rd s b counter removed for roadworks,53.358600,-6.241120,CYC
15,richmond street inbound,53.332160,-6.264400,CYC
16,richmond street outbound,53.332160,-6.264400,CYC
17,rock road bus lane,53.308690,-6.195510,CYC
18,rock road totem inbound,53.308120,-6.195030,CYC
19,wyattville rd bicycles from n11,53.250970,-6.132980,CYC
20,aston quay fitzgeralds,53.346680,-6.259880,FTF
21,bachelors walk bachelors way,53.347440,-6.260100,FTF
22,baggot st lower wilton tce inbound,53.334540,-6.245620,FTF
23,baggot st upper mespil rd bank,53.333770,-6.244510,FTF
24,capel st mary street,53.348530,-6.268800,FTF
25,college green bank of ireland,53.345340,-6.259240,FTF
26,college green church lane,53.344410,53.344410,FTF
27,college st westmoreland st,53.345060,-6.258880,FTF
28,d olier st burgh quay,53.346840,-6.258870,FTF
29,dame street londis,53.344470,-6.261520,FTF
30,dawson street,53.341194,-6.258337,FTF
31,dawson street molesworth,53.341430,-6.258050,FTF
32,dawson street old,53.342176,-6.258023,FTF
33,grafton st monsoon,53.340770,-6.260580,FTF
34,grafton street compub,53.343710,-6.259960,FTF
35,grafton street nassau street suffolk street,53.343550,-6.259320,FTF
36,grand canal st upp clanwilliam place,53.338480,-6.237940,FTF
37,grand canal st upp clanwilliam place google,53.338550,-6.238980,FTF
38,henry street coles lane dunnes,53.348760,-6.262860,FTF
39,henry street outside dunnes stores,53.329644,-6.270178,FTF
40,liffey st halfpenny bridge,53.346820,-6.263330,FTF
41,liffey street old,53.346725,-6.263270,FTF
42,mary st jervis st,53.348650,-6.266850,FTF
43,morton stadium swords,53.401253,-6.243014,FTF
44,n11 outbound montrose,53.306730,-6.212780,FTF
45,n11 totem inbound,53.307094,-6.213874,FTF
46,newcomen bridge charleville mall inbound remov...,53.356450,-6.244180,FTF
47,newcomen bridge charleville mall outbound remo...,53.356480,-6.244180,FTF
48,north wall quay samuel beckett bridge east,53.347460,-6.240990,FTF
49,north wall quay samuel beckett bridge west,53.347500,-6.241400,FTF
50,o connell st parnell st aib,53.352510,-6.261780,FTF
51,o connell st pennys,53.348790,-6.259690,FTF
52,o connell st princes st north,53.348950,-6.260040,FTF
53,o connell street pennys pyro evo temporary cou...,53.346935,-6.259110,FTF
54,phibsborough rd enniskerry road,53.363540,-6.272080,FTF
55,phibsborough rd munster st removed due to over...,53.363220,-6.272470,FTF
56,richmond st south portabello harbour inbound,53.330420,-6.264480,FTF
57,richmond st south portabello harbour outbound,53.330330,-6.264250,FTF
58,round tower entrance,53.322473,-6.395453,FTF
59,round tower upstairs,53.322361,-6.395447,FTF
60,talbot st guineys,53.350820,-6.255400,FTF
61,talbot st murrays pharmacy,53.350535,-6.253992,FTF
62,westmoreland east old,53.346045,-6.258960,FTF
63,westmoreland street east fleet street removed ...,53.345310,-6.259330,FTF
64,westmoreland street west carrolls,53.346480,-6.259180,FTF
65,westmoreland west old,53.346034,-6.259275,FTF
66,wyattville road at steps decommissioned coun,53.251143,-6.132456,FTF
67,corkagh park location 1 n7,53.305930,-6.412300,FTF_CYC
68,corkagh park location 2 grange castle,53.309960,-6.422330,FTF_CYC
69,corkagh park location 3 cherrywood,53.315520,-6.414770,FTF_CYC
70,corkagh park location 4 main car park,53.315430,-6.410300,FTF_CYC
71,corkagh park location 5 main car park,53.315580,-6.409530,FTF_CYC
72,corkagh park location 6 fonthill,53.317170,-6.410560,FTF_CYC
73,dodder valley park 1,53.282210,-6.343920,FTF_CYC
74,dodder valley park 2,53.281980,-6.347730,FTF_CYC
75,dodder valley park 3,53.278990,-6.356460,FTF_CYC
76,drumcondra cyclists inbound,53.363670,-6.257430,FTF_CYC
77,dun laoghaire peoples park,53.291780,-6.128860,FTF_CYC
78,dun laoghaire seapoint beach,53.297320,-6.160740,FTF_CYC
79,dun laoghaire york road,53.296080,-6.142580,FTF_CYC
80,glenageary,53.281410,-6.123190,FTF_CYC
81,grand canal cycle path lock c5,53.331830,-6.254690,FTF_CYC
82,portmarnock greenway,53.409854,-6.136893,FTF_CYC
83,rock road park ped s cyclists,53.308770,-6.195630,FTF_CYC
84,wyattville rd at park gates,53.251410,-6.132950,FTF_CYC
85,wyattville rd bicycles towards n11,53.251040,-6.132450,FTF_CYC

In [ ]:
matches = {
 "CYC_Clontarf James Larkin Rd" : "clontarf james larkin rd	",
 "CYC_Clontarf Pebble Beach Carpark" : "clontarf pebble beach carpark",
 "CYC_Grove Road Totem" : "grove road totem",
 "CYC_North Strand Rd N B": "north strand rd n b counter removed for roadworks",
 "CYC_Richmond Street Cyclists 1 Merged": "richmond street inbound",
 "CYC_Richmond Street Cyclists 2 Merged": "richmond street outbound",
 "FTF_Aston Quay Merged": "aston quay fitzgeralds",
 "FTF_Bachelors Walk Merged": "bachelors walk bachelors way",
 "FTF_Capel St Mary St Merged" : "capel st mary street",
 "FTF_College St Dame St Merged" : "college st westmoreland st",
 "FTF_Dame St Merged" : "dame street londis",
 "FTF_Dolier St Burgh Quay Merged" : "d olier st burgh quay",
 "FTF_Grafton St Monsoon Merged" : "grafton st monsoon",
 "FTF_Grafton St Nassau St Suffolk St" : "grafton street nassau street suffolk street",
 "FTF_Henry St Merged" : "henry street coles lane dunnes	",
 "FTF_Mary St Merged" : "mary st jervis st",
 "FTF_Oconnell St Princes St North Merged" : "o connell st princes st north",
 "FTF_Oconnell St Pennys Merged" : "o connell st pennys",
 "FTF_Talbot St Guineys Merged" : "talbot st guineys",
 "FTF_Talbot St Murrays Pharmacy Merged" : "talbot st murrays pharmacy",
 "FTF_Westmoreland St East Fleet St Merged" : "westmoreland street east fleet street removed to return to supplier",
 "FTF_Westmoreland St West Merged" : "westmoreland street west carrolls",
 "FTF_Baggot St Upper Mespil Rd Bank": "baggot st upper mespil rd bank",
 "FTF_Baggot St Lower Merged": "baggot st lower wilton tce inbound",
 "FTF_Dawson St Merged": "dawson street",
 "FTF_Grand Canal St Upper Clanwilliam Place Google Merged": "grand canal st upp clanwilliam place google",
 "FTF_North Wall Quay Samuel Beckett Bridge East": "north wall quay samuel beckett bridge east",
 "FTF_North Wall Quay Samuel Beckett Bridge West": "north wall quay samuel beckett bridge west",
 "FTF_Phibsborough Rd Enniskerry Road": "phibsborough rd enniskerry road",
 "FTF_Richmond St South Portabello Harbour Inbound": "richmond st south portabello harbour inbound",
 "FTF_Richmond St South Portabello Harbour Outbound": "richmond st south portabello harbour outbound",
}

In [ ]:
# Invert dictionary to look for the value
inverse_matches = {v.strip().lower(): k for k, v in matches.items()}

# Normalise text in column to make match
counters["Bike Counter Locations_norm"] = counters["Bike Counter Locations"].str.strip().str.lower()

# Replace values with reversed dictionary
counters["Bike Counter Locations"] = counters["Bike Counter Locations_norm"].map(inverse_matches)

counters = counters.drop(columns=["Bike Counter Locations_norm"])
counters = counters.dropna(subset=["Bike Counter Locations"])
counters = counters.drop(columns=["User Type"])

In [ ]:
counters.rename(columns={
    "Bike Counter Locations": "Target",
}, inplace=True)

counters

                                               Target   Latitude  Longitude
3                        CYC_Clontarf James Larkin Rd  53.368540  -6.170320
4                   CYC_Clontarf Pebble Beach Carpark  53.358250  -6.191070
11                               CYC_Grove Road Totem  53.329644  -6.270178
13                            CYC_North Strand Rd N B  53.358520  -6.241270
15              CYC_Richmond Street Cyclists 1 Merged  53.332160  -6.264400
16              CYC_Richmond Street Cyclists 2 Merged  53.332160  -6.264400
20                              FTF_Aston Quay Merged  53.346680  -6.259880
21                          FTF_Bachelors Walk Merged  53.347440  -6.260100
22                         FTF_Baggot St Lower Merged  53.334540  -6.245620
23                 FTF_Baggot St Upper Mespil Rd Bank  53.333770  -6.244510
24                        FTF_Capel St Mary St Merged  53.348530  -6.268800
27                      FTF_College St Dame St Merged  53.345060  -6.258880
28                    FTF_Dolier St Burgh Quay Merged  53.346840  -6.258870
29                                 FTF_Dame St Merged  53.344470  -6.261520
30                               FTF_Dawson St Merged  53.341194  -6.258337
33                      FTF_Grafton St Monsoon Merged  53.340770  -6.260580
35                FTF_Grafton St Nassau St Suffolk St  53.343550  -6.259320
37  FTF_Grand Canal St Upper Clanwilliam Place Goo...  53.338550  -6.238980
38                                FTF_Henry St Merged  53.348760  -6.262860
42                                 FTF_Mary St Merged  53.348650  -6.266850
48     FTF_North Wall Quay Samuel Beckett Bridge East  53.347460  -6.240990
49     FTF_North Wall Quay Samuel Beckett Bridge West  53.347500  -6.241400
51                      FTF_Oconnell St Pennys Merged  53.348790  -6.259690
52            FTF_Oconnell St Princes St North Merged  53.348950  -6.260040
54                FTF_Phibsborough Rd Enniskerry Road  53.363540  -6.272080
56   FTF_Richmond St South Portabello Harbour Inbound  53.330420  -6.264480
57  FTF_Richmond St South Portabello Harbour Outbound  53.330330  -6.264250
60                       FTF_Talbot St Guineys Merged  53.350820  -6.255400
61              FTF_Talbot St Murrays Pharmacy Merged  53.350535  -6.253992
63           FTF_Westmoreland St East Fleet St Merged  53.345310  -6.259330
64                    FTF_Westmoreland St West Merged  53.346480  -6.259180

## **SAVE TO BLOB**

In [ ]:
def save_to_blob(data, filename):
    try:
        blob_name = f"{CONTAINER_NAME}/{filename}"
        csv_data = data.to_csv(index=False)
        with fs.open(blob_name, 'w') as f:
            f.write(csv_data)
        print(f"Saved to {blob_name}")
    except Exception as e:
        print(f"Error saving data to blob storage: {str(e)}")
        return False

In [ ]:
CONTAINER_NAME = "preprocessed"

save_to_blob(counters, "counters.csv")

Saved to preprocessed/counters.csv