# **DEEP LEARNING MODELLING: CNN-LSTM USING GEOGRAPHICAL COORDINATES**

## **1. LIBRARIES**

### **1.1 DEPENDENCIES**

In [ ]:
! pip install adlfs azure-storage-blob
! pip install tensorflow
! pip install tqdm

Collecting adlfs
  Downloading adlfs-2024.12.0-py3-none-any.whl.metadata (7.7 kB)
Collecting azure-storage-blob
  Downloading azure_storage_blob-12.26.0-py3-none-any.whl.metadata (26 kB)
Collecting azure-core<2.0.0,>=1.28.0 (from adlfs)
  Downloading azure_core-1.35.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 4.4 MB/s eta 0:00:00
Collecting azure-datalake-store<0.1,>=0.0.53 (from adlfs)
  Downloading azure_datalake_store-0.0.53-py2.py3-none-any.whl.metadata (19 kB)
Collecting azure-identity (from adlfs)
  Downloading azure_identity-1.24.0-py3-none-any.whl.metadata (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 8.3 MB/s eta 0:00:00
Requirement already satisfied: fsspec>=2023.12.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (2025.3.0)
Requirement already satisfied: aiohttp>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (3.12.15)
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (43.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (4.14.1)
Collecting isodate>=0.6.1 (from azure-storage-blob)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.20.1)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (2.32.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (1.17.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.17.1)
Collecting msal<2,>=1.16.0 (from azure-datalake-store<0.1,>=0.0.53->adlfs)
  Downloading msal-1.33.0-py3-none-any.whl.metadata (11 kB)
Collecting msal-extensions>=1.2.0 (from azure-identity->adlfs)
  Downloading msal_extensions-1.3.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.22)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from PyJWT[crypto]<3,>=1.0.0->msal<2,>=1.16.0->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.10.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2025.8.3)
Downloading adlfs-2024.12.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 4.3 MB/s eta 0:00:00
Downloading azure_storage_blob-12.26.0-py3-none-any.whl (412 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.9/412.9 kB 37.7 MB/s eta 0:00:00
Downloading azure_core-1.35.0-py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 kB 22.3 MB/s eta 0:00:00
Downloading azure_datalake_store-0.0.53-py2.py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 5.7 MB/s eta 0:00:00
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Downloading azure_identity-1.24.0-py3-none-any.whl (187 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.9/187.9 kB 18.6 MB/s eta 0:00:00
Downloading msal-1.33.0-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.9/116.9 kB 11.3 MB/s eta 0:00:00
Downloading msal_extensions-1.3.1-py3-none-any.whl (20 kB)
Installing collected packages: isodate, azure-core, azure-storage-blob, msal, msal-extensions, azure-datalake-store, azure-identity, adlfs
Successfully installed adlfs-2024.12.0 azure-core-1.35.0 azure-datalake-store-0.0.53 azure-identity-1.24.0 azure-storage-blob-12.26.0 isodate-0.7.2 msal-1.33.0 msal-extensions-1.3.1
Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)

### **1.2 LIBRARIES**

In [ ]:
# STANDARD LIBRARY
import os
import io
import random

# DATA MANIPULATION AND ANALYSIS
import pandas as pd
import numpy as np

# DATA VISUALISATION
import matplotlib.pyplot as plt
import seaborn as sns

# AZURE CLOUD STORAGE
from adlfs import AzureBlobFileSystem
from azure.storage.blob import BlobServiceClient

# REGULAR EXPRESSIONS
import re

# TIME SERIES
from sklearn.model_selection import TimeSeriesSplit

# STANDARIZATION
from sklearn.preprocessing import StandardScaler

# EVALUATION METRICS
from sklearn.metrics import r2_score

# PROGRESS BAR
from tqdm import tqdm

# TENSORFLOW
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Conv1D, BatchNormalization, Dropout, LSTM, Dense, Input
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy("mixed_float16")
from sklearn.preprocessing import RobustScaler
from tensorflow.keras.losses import Huber

In [ ]:
# SEEDS
random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
print(tf.__version__)

2.19.0

In [ ]:
# Correctly set pandas display option for max columns and rows
pd.options.display.max_columns = None
pd.options.display.max_rows = None

## **2. LOADING DATASETS FROM AZURE BLOB STORAGE**

In [ ]:
def load_csv_from_blob(blob_name):
    blob_client = container_client.get_blob_client(blob_name)
    stream = blob_client.download_blob()
    data_bytes = stream.readall()
    data_str = data_bytes.decode("utf-8")
    return pd.read_csv(io.StringIO(data_str))


# Connection configuration
AZURE_STORAGE_ACCOUNT = "researchprojectx24104515"
AZURE_STORAGE_KEY = "bxpexO6i+Hz6n1WiipTn+sTCuLPGMS1BogMERrIrHd16DpQ0GLfQ0R33yrSw4MxsDomq5yNMgw1o+AStlx/MjA=="
connection_string = f"DefaultEndpointsProtocol=https;AccountName={AZURE_STORAGE_ACCOUNT};AccountKey={AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net"
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

fs = AzureBlobFileSystem(
    account_name=AZURE_STORAGE_ACCOUNT,
    account_key=AZURE_STORAGE_KEY
)

In [ ]:
# Establish connection to cycle
CONTAINER_NAME = "preprocessed"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "preprocessed.csv"
data = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {data.shape}")

Loaded 'preprocessed.csv' with shape: (53424, 44)

In [ ]:
print("Preprocessed Data:")
print(data.shape)
data.head()

Preprocessed Data:
(53424, 44)

,date and time,CYC_Clontarf James Larkin Rd,CYC_Clontarf Pebble Beach Carpark,CYC_Grove Road Totem,CYC_North Strand Rd N B,CYC_Richmond Street Cyclists 1 Merged,CYC_Richmond Street Cyclists 2 Merged,FTF_Aston Quay Merged,FTF_Capel St Mary St Merged,FTF_College St Dame St Merged,FTF_Dame St Merged,FTF_Dolier St Burgh Quay Merged,FTF_Grafton St Monsoon Merged,FTF_Grafton St Nassau St Suffolk St,FTF_Henry St Merged,FTF_Mary St Merged,FTF_Oconnell St Princes St North Merged,FTF_Talbot St Guineys Merged,FTF_Westmoreland St East Fleet St Merged,FTF_Westmoreland St West Merged,WTH_rain,WTH_temp,WTH_wetb,WTH_dewpt,WTH_vappr,WTH_rhum,WTH_msl,TEMP_year,TEMP_holiday,WTH_temp_3h,WTH_rain_int,WTH_dew_spread,WTH_prob_cond,WTH_severe,TEMP_hour_sin,TEMP_hour_cos,TEMP_day_sin,TEMP_day_cos,TEMP_month_sin,TEMP_month_cos,TEMP_weekend,TEMP_mor_peak,TEMP_eve_peak,TEMP_bus_hours
0,2019-01-01 00:00:00,0.0,0.0,12.0,16.0,0.0,0.0,0.0,238.0,0.0,0.0,0.0,140.0,0.0,597.0,163.0,1914.0,0.0,1670.0,1988.0,0.0,9.6,7.8,5.6,9.1,76.0,1035.1,2019,0,0.000000,0,4.0,0,0,0.000000,1.000000,0.781831,0.62349,0.5,0.866025,0,0,0,0
1,2019-01-01 01:00:00,0.0,0.0,17.0,14.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,215.0,0.0,359.0,102.0,885.0,0.0,767.0,1270.0,0.0,8.6,7.1,5.3,8.9,79.0,1035.1,2019,0,0.000000,0,3.3,0,0,0.258819,0.965926,0.781831,0.62349,0.5,0.866025,0,0,0,0
2,2019-01-01 02:00:00,0.0,0.0,18.0,9.0,0.0,0.0,0.0,121.0,0.0,0.0,0.0,210.0,0.0,317.0,63.0,984.0,0.0,642.0,1589.0,0.0,8.3,6.9,5.3,8.9,81.0,1034.9,2019,0,8.833333,0,3.0,0,0,0.500000,0.866025,0.781831,0.62349,0.5,0.866025,0,0,0,0
3,2019-01-01 03:00:00,0.0,0.0,18.0,15.0,0.0,0.0,0.0,174.0,0.0,0.0,0.0,204.0,0.0,313.0,59.0,935.0,0.0,582.0,1534.0,0.0,9.1,7.6,5.8,9.2,79.0,1035.5,2019,0,8.666667,0,3.3,0,0,0.707107,0.707107,0.781831,0.62349,0.5,0.866025,0,0,0,0
4,2019-01-01 04:00:00,0.0,0.0,12.0,8.0,0.0,0.0,0.0,82.0,0.0,0.0,0.0,88.0,0.0,172.0,46.0,390.0,0.0,143.0,610.0,0.0,9.2,7.7,5.9,9.3,79.0,1035.7,2019,0,8.866667,0,3.3,0,0,0.866025,0.500000,0.781831,0.62349,0.5,0.866025,0,0,0,0

In [ ]:
# Establish connection to counters dataset
CONTAINER_NAME = "preprocessed"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "counters.csv"
counters = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {counters.shape}")

Loaded 'counters.csv' with shape: (31, 3)

In [ ]:
print("Counter Locations Data:")
print(counters.shape)
counters

Counter Locations Data:
(31, 3)

                                               Target   Latitude  Longitude
0                        CYC_Clontarf James Larkin Rd  53.368540  -6.170320
1                   CYC_Clontarf Pebble Beach Carpark  53.358250  -6.191070
2                                CYC_Grove Road Totem  53.329644  -6.270178
3                             CYC_North Strand Rd N B  53.358520  -6.241270
4               CYC_Richmond Street Cyclists 1 Merged  53.332160  -6.264400
5               CYC_Richmond Street Cyclists 2 Merged  53.332160  -6.264400
6                               FTF_Aston Quay Merged  53.346680  -6.259880
7                           FTF_Bachelors Walk Merged  53.347440  -6.260100
8                          FTF_Baggot St Lower Merged  53.334540  -6.245620
9                  FTF_Baggot St Upper Mespil Rd Bank  53.333770  -6.244510
10                        FTF_Capel St Mary St Merged  53.348530  -6.268800
11                      FTF_College St Dame St Merged  53.345060  -6.258880
12                    FTF_Dolier St Burgh Quay Merged  53.346840  -6.258870
13                                 FTF_Dame St Merged  53.344470  -6.261520
14                               FTF_Dawson St Merged  53.341194  -6.258337
15                      FTF_Grafton St Monsoon Merged  53.340770  -6.260580
16                FTF_Grafton St Nassau St Suffolk St  53.343550  -6.259320
17  FTF_Grand Canal St Upper Clanwilliam Place Goo...  53.338550  -6.238980
18                                FTF_Henry St Merged  53.348760  -6.262860
19                                 FTF_Mary St Merged  53.348650  -6.266850
20     FTF_North Wall Quay Samuel Beckett Bridge East  53.347460  -6.240990
21     FTF_North Wall Quay Samuel Beckett Bridge West  53.347500  -6.241400
22                      FTF_Oconnell St Pennys Merged  53.348790  -6.259690
23            FTF_Oconnell St Princes St North Merged  53.348950  -6.260040
24                FTF_Phibsborough Rd Enniskerry Road  53.363540  -6.272080
25   FTF_Richmond St South Portabello Harbour Inbound  53.330420  -6.264480
26  FTF_Richmond St South Portabello Harbour Outbound  53.330330  -6.264250
27                       FTF_Talbot St Guineys Merged  53.350820  -6.255400
28              FTF_Talbot St Murrays Pharmacy Merged  53.350535  -6.253992
29           FTF_Westmoreland St East Fleet St Merged  53.345310  -6.259330
30                    FTF_Westmoreland St West Merged  53.346480  -6.259180

### **2.1 DEFINE FEATURE CATEGORIES**

In [ ]:
# Interaction features created with weather features
interactionf = ["WTH_dew_spread", "WTH_prob_cond", "WTH_severe"]

# Using regex to get all temporal and weather prefix patterns
temp_pattern = re.compile(r"^TEMP_")
wth_patterb = re.compile(r"^WTH_")

# Using regex to get all temporal and weather features
temporalf = [col for col in data.columns if temp_pattern.match(col)]
weatherf = [col for col in data.columns if wth_patterb.match(col) and col not in interactionf]

In [ ]:
weatherf

['WTH_rain',
 'WTH_temp',
 'WTH_wetb',
 'WTH_dewpt',
 'WTH_vappr',
 'WTH_rhum',
 'WTH_msl',
 'WTH_temp_3h',
 'WTH_rain_int']

In [ ]:
temporalf

['TEMP_year',
 'TEMP_holiday',
 'TEMP_hour_sin',
 'TEMP_hour_cos',
 'TEMP_day_sin',
 'TEMP_day_cos',
 'TEMP_month_sin',
 'TEMP_month_cos',
 'TEMP_weekend',
 'TEMP_mor_peak',
 'TEMP_eve_peak',
 'TEMP_bus_hours']

In [ ]:
# Combine all features
fcolumns = weatherf + temporalf + interactionf

# Extract cycle and footfall targets
cycle_t = [col for col in data.columns if col.startswith("CYC_")]
footfall_t = [col for col in data.columns if col.startswith("FTF_")]
targets = cycle_t + footfall_t

# Prepare feature matrix
X = data[fcolumns].copy()
y = data[targets].copy()

# Handle missing values
X = X.ffill().bfill()
y = y.fillna(0)

print(f"Features shape: {X.shape}")
print(f"Targets shape: {y.shape}")
print(f"Feature columns: {len(fcolumns)}")

Features shape: (53424, 24)
Targets shape: (53424, 19)
Feature columns: 24

In [ ]:
targets

['CYC_Clontarf James Larkin Rd',
 'CYC_Clontarf Pebble Beach Carpark',
 'CYC_Grove Road Totem',
 'CYC_North Strand Rd N B',
 'CYC_Richmond Street Cyclists 1 Merged',
 'CYC_Richmond Street Cyclists 2 Merged',
 'FTF_Aston Quay Merged',
 'FTF_Capel St Mary St Merged',
 'FTF_College St Dame St Merged',
 'FTF_Dame St Merged',
 'FTF_Dolier St Burgh Quay Merged',
 'FTF_Grafton St Monsoon Merged',
 'FTF_Grafton St Nassau St Suffolk St',
 'FTF_Henry St Merged',
 'FTF_Mary St Merged',
 'FTF_Oconnell St Princes St North Merged',
 'FTF_Talbot St Guineys Merged',
 'FTF_Westmoreland St East Fleet St Merged',
 'FTF_Westmoreland St West Merged']

## **3. CNN / LSTM**

### **3.1 DEFINE CNN-LSTM SEQUENCES AND TIME SERIES SPLIT**

In [ ]:
# Create CNN-LSTM sequences

def cnnlstm_seqs(data, targets, features, counters, seq_len=24):

    # Scale all features
    f_scaler = MinMaxScaler()
    features = f_scaler.fit_transform(data[features])

    # Containers for results
    X_data = {}
    y_data = {}
    t_scalers = {}

    # Processing separately each target
    for t in targets:
        # Coordinates from the target
        lat = counters.loc[counters["Target"] == t, "Latitude"].values[0]
        lon = counters.loc[counters["Target"] == t, "Longitude"].values[0]

        # Extract target column and reshape to 2D
        y = data[t].values.reshape(-1, 1)

        # Fitting a scaler
        t_scaler = MinMaxScaler()
        y_scaled = t_scaler.fit_transform(y)
        X, y_seq = [], []

        # Create sliding window sequences
        for i in range(seq_len, len(features)):
            seq = features[i-seq_len:i]

            # Create a sequence lenght × 2 array with repeated coordinates
            coords = np.tile([lat, lon], (seq_len, 1))

            #Concatenate sequences with coordinates
            seq_with_coords = np.concatenate([seq, coords], axis=1)
            X.append(seq_with_coords)
            y_seq.append(y_scaled[i])

        # Converting data to NumPy arrays to store in dictionaries
        X_data[t] = np.array(X, dtype=np.float32)
        y_data[t] = np.array(y_seq, dtype=np.float32)
        t_scalers[t] = t_scaler

    return X_data, y_data, f_scaler, t_scalers


# Time Series Split
def ts_split(X, y, train_ratio=0.7, val_ratio=0.15):

    # Total number of sequences
    n_samples = len(X)

    # Index boundaeries calculated by ratios
    train_end = int(n_samples * train_ratio)
    val_end = int(n_samples * (train_ratio + val_ratio))

    # Slice sets sequentially as a Time Series
    X_train = X[:train_end]
    y_train = y[:train_end]
    X_val = X[train_end:val_end]
    y_val = y[train_end:val_end]
    X_test = X[val_end:]
    y_test = y[val_end:]

    return X_train, X_val, X_test, y_train, y_val, y_test

### **3.2 BUILD CNN-LSTM MODEL**

In [ ]:
def build_cnnlstm(input_shape, conv_filters=64, lstm_units=64, dense_units=64, dropout_rate=0.2):
    # Level 2 regularisation
    reg = 1e-4

    # Batch Normalization for Training stabilisation and Dropout to avoid overfitting

    # Model
    model = Sequential()
    model.add(Input(shape=input_shape))

    # FEATURE EXTRACTION
    # First convolutional layer for feature extraction from short-term sequential data
    model.add(Conv1D(conv_filters, 3, activation="relu", padding="same",
                     kernel_regularizer=regularizers.l2(reg)))
    model.add(BatchNormalization())
    model.add(Dropout(dropout_rate))

    # Second convolutional layer for more abstract features and long-term temporal patterns
    model.add(Conv1D(conv_filters//2, 5, activation="relu", padding="same",
                     kernel_regularizer=regularizers.l2(reg)))
    model.add(BatchNormalization())
    model.add(Dropout(dropout_rate))

    # LSTM FOR LONG TERM DEPENDENCIES
    # First LSTM layer, returns to a sequence that keeps temporal information
    model.add(LSTM(lstm_units, return_sequences=True, dropout=dropout_rate, recurrent_dropout=dropout_rate,
                   kernel_regularizer=regularizers.l2(reg)))
    model.add(Dropout(dropout_rate))

    # Second LSTM layer, returns to a single output
    model.add(LSTM(lstm_units//2, return_sequences=False, dropout=dropout_rate, recurrent_dropout=dropout_rate,
                   kernel_regularizer=regularizers.l2(reg)))
    model.add(Dropout(dropout_rate))

    # Dense layer for learned features before final prediction
    model.add(Dense(dense_units, activation="relu", kernel_regularizer=regularizers.l2(reg)))
    model.add(Dropout(dropout_rate))

    # Single output neuron with no negative predictions
    model.add(Dense(1, activation="relu"))

    # Model compilation
    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss=Huber(delta=1.0),
        metrics=["mae"]
    )
    return model

### **3.3 TRAIN MODEL**

In [ ]:
# TRAIN MODEL
def train_cnnlstm(target_name, X, y, callbacks=None):

    # Training starts
    print(f"\nTraining model for: {target_name}")

    # Split the sequences into train, test and validation sets
    X_train, X_val, X_test, y_train, y_val, y_test = ts_split(X, y)

    # CNN-LSTM model built with an input shape that matches the sequences
    model = build_cnnlstm(input_shape=X_train.shape[1:])

    # If not callbacks provided, use this as default
    if callbacks is None:
        # Stop if validation loss stops improving for 10 epochs
        early_stopping = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)
        # Reduce learning rate if validation loss doe not improve after 5 epochs
        reduce_lr = ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=5, min_lr=1e-6)
        callbacks = [early_stopping, reduce_lr]

    # Train the model
    history = model.fit(
        X_train, y_train,
        # Maximum training Epochs
        epochs=100,
        # Large batch size for training efficiency
        batch_size=1024,
        # Monitor performance on validation set
        validation_data=(X_val, y_val),
        # Apply early stop or reduce learning rate
        callbacks=callbacks,
        # Shows training process
        verbose=1
    )

    print(f"------Training completed for: {target_name}")
    return model, history, X_test, y_test

### **3.4 EVALUTAION**

In [ ]:
def evaluate_mtarget(model, X_test, y_test, target_scaler, target_name, target_idx, n_targets):
    print(f"\n----- Evaluating model for: {target_name} ({target_idx + 1}/{n_targets})")

    # Predictions
    y_pred = model.predict(X_test)

    # Inverse transfomation of y_pred and predictions
    y_true = target_scaler.inverse_transform(y_test.reshape(-1, 1))
    y_pred = target_scaler.inverse_transform(y_pred)

    # Round to whole numbers
    y_pred = np.round(y_pred).astype(int)
    y_true = np.round(y_true).astype(int)

    # Evaluation metrics
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    mae = np.mean(np.abs(y_true - y_pred))
    mask = y_true != 0
    mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100 if np.any(mask) else np.nan
    r2 = r2_score(y_true, y_pred)

    # Evalation metrics print
    print("Evaluation Metrics:")
    print(f" -RMSE : {rmse:.2f}")
    print(f" -MAE  : {mae:.2f}")
    print(f" -MAPE : {mape:.2f}%")
    print(f" -R²   : {r2:.4f}")

    return {
        "RMSE": rmse,
        "MAE": mae,
        "MAPE": mape,
        "R2": r2
    }

### **3.5 APPLYING CNN-LSTM**

In [ ]:
# APPLY CNN LSTM

# Number of time steps per sequence
sequence_length = 24

# Prepare CNN-LSTM sequences (features and coordinates for each timestep)
X_cnn_lstm_dict, y_cnn_lstm_dict, feature_scaler_lstm, target_scaler_dict = cnnlstm_seqs(
    # Combines features (X) with targets (Y) into a DataFrames, including coordinates
    pd.concat([X, y], axis=1),
    targets,
    fcolumns,
    counters,
    sequence_length
)

# Shape of sequence
print("Shape of a sequence with coordinates:", X_cnn_lstm_dict[targets[0]].shape)

# Dictionaries to store results for all targets
models = {}
histories = {}
results = {}
test_sets = {}

# Total number of target variables
n_targets = len(targets)

# Train and evaluate model for each target
for idx, target_name in enumerate(targets, 1):
    print(f"\n--- Processing target {idx} out of {n_targets}: {target_name}")

    # Retrieve the prepared sequences for this target
    X_data = X_cnn_lstm_dict[target_name]
    y_data = y_cnn_lstm_dict[target_name]

    # Train the model with early stopping
    model, history, X_test, y_test = train_cnnlstm(
        target_name,
        X_data,
        y_data,
        callbacks=[EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)]
    )

    # Store the models and training history
    models[target_name] = model
    histories[target_name] = history
    test_sets[target_name] = (X_test, y_test)
    target_scaler = target_scaler_dict[target_name]

    # Evaluate the performance of the model on test set
    metrics = evaluate_mtarget(
        model,
        X_test,
        y_test,
        target_scaler,
        target_name,
        idx,
        n_targets
    )

    # Save the metrics for the evaluated target
    results[target_name] = metrics

print("\nTraining and evaluation completed for all targets.")

Shape of a sequence with coordinates: (53400, 24, 26)

--- Processing target 1 out of 19: CYC_Clontarf James Larkin Rd

Training model for: CYC_Clontarf James Larkin Rd
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 19s 158ms/step - loss: 0.0286 - mae: 0.0501 - val_loss: 0.0234 - val_mae: 0.0750
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0177 - mae: 0.0342 - val_loss: 0.0171 - val_mae: 0.0750
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0114 - mae: 0.0291 - val_loss: 0.0133 - val_mae: 0.0750
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0077 - mae: 0.0252 - val_loss: 0.0110 - val_mae: 0.0750
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0054 - mae: 0.0215 - val_loss: 0.0096 - val_mae: 0.0750
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0040 - mae: 0.0200 - val_loss: 0.0056 - val_mae: 0.0645
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0032 - mae: 0.0199 - val_loss: 0.0082 - val_mae: 0.0750
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0025 - mae: 0.0185 - val_loss: 0.0108 - val_mae: 0.1275
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0021 - mae: 0.0180 - val_loss: 0.0091 - val_mae: 0.1163
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0018 - mae: 0.0176 - val_loss: 0.0083 - val_mae: 0.1113
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0016 - mae: 0.0172 - val_loss: 0.0153 - val_mae: 0.1626
------Training completed for: CYC_Clontarf James Larkin Rd

----- Evaluating model for: CYC_Clontarf James Larkin Rd (2/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step
Evaluation Metrics:
 -RMSE : 55.65
 -MAE  : 50.29
 -MAPE : 1126.31%
 -R²   : -1.0936

--- Processing target 2 out of 19: CYC_Clontarf Pebble Beach Carpark

Training model for: CYC_Clontarf Pebble Beach Carpark
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 158ms/step - loss: 0.0273 - mae: 0.0436 - val_loss: 0.0271 - val_mae: 0.1432
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0153 - mae: 0.0322 - val_loss: 0.0163 - val_mae: 0.0831
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0092 - mae: 0.0272 - val_loss: 0.0128 - val_mae: 0.0831
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0057 - mae: 0.0230 - val_loss: 0.0109 - val_mae: 0.0831
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0039 - mae: 0.0213 - val_loss: 0.0092 - val_mae: 0.0799
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0029 - mae: 0.0200 - val_loss: 0.0208 - val_mae: 0.1874
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0022 - mae: 0.0185 - val_loss: 0.0175 - val_mae: 0.1705
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0019 - mae: 0.0191 - val_loss: 0.0051 - val_mae: 0.0578
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0016 - mae: 0.0177 - val_loss: 0.0040 - val_mae: 0.0683
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0015 - mae: 0.0180 - val_loss: 0.0031 - val_mae: 0.0536
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0014 - mae: 0.0185 - val_loss: 0.0020 - val_mae: 0.0371
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0013 - mae: 0.0174 - val_loss: 0.0039 - val_mae: 0.0532
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0012 - mae: 0.0170 - val_loss: 0.0032 - val_mae: 0.0454
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0012 - mae: 0.0170 - val_loss: 0.0016 - val_mae: 0.0312
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0011 - mae: 0.0171 - val_loss: 0.0019 - val_mae: 0.0369
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0011 - mae: 0.0167 - val_loss: 0.0027 - val_mae: 0.0407
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0012 - mae: 0.0175 - val_loss: 0.0057 - val_mae: 0.0656
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0012 - mae: 0.0180 - val_loss: 0.0036 - val_mae: 0.0495
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0011 - mae: 0.0172 - val_loss: 0.0079 - val_mae: 0.0826
------Training completed for: CYC_Clontarf Pebble Beach Carpark

----- Evaluating model for: CYC_Clontarf Pebble Beach Carpark (3/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step
Evaluation Metrics:
 -RMSE : 29.96
 -MAE  : 18.66
 -MAPE : 64.68%
 -R²   : 0.7012

--- Processing target 3 out of 19: CYC_Grove Road Totem

Training model for: CYC_Grove Road Totem
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 148ms/step - loss: 0.0304 - mae: 0.0718 - val_loss: 0.0238 - val_mae: 0.0684
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0195 - mae: 0.0533 - val_loss: 0.0184 - val_mae: 0.0787
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0129 - mae: 0.0475 - val_loss: 0.0121 - val_mae: 0.0779
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 121ms/step - loss: 0.0089 - mae: 0.0422 - val_loss: 0.0129 - val_mae: 0.1166
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0066 - mae: 0.0391 - val_loss: 0.0112 - val_mae: 0.1127
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0051 - mae: 0.0364 - val_loss: 0.0119 - val_mae: 0.1282
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0043 - mae: 0.0357 - val_loss: 0.0579 - val_mae: 0.3251
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0036 - mae: 0.0344 - val_loss: 0.0057 - val_mae: 0.0759
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0031 - mae: 0.0328 - val_loss: 0.0054 - val_mae: 0.0566
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0028 - mae: 0.0318 - val_loss: 0.0057 - val_mae: 0.0541
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0026 - mae: 0.0315 - val_loss: 0.0037 - val_mae: 0.0413
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0023 - mae: 0.0304 - val_loss: 0.0057 - val_mae: 0.0536
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0022 - mae: 0.0302 - val_loss: 0.0103 - val_mae: 0.0918
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0021 - mae: 0.0299 - val_loss: 0.0108 - val_mae: 0.0952
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0021 - mae: 0.0301 - val_loss: 0.0106 - val_mae: 0.0947
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0020 - mae: 0.0294 - val_loss: 0.0085 - val_mae: 0.0794
------Training completed for: CYC_Grove Road Totem

----- Evaluating model for: CYC_Grove Road Totem (4/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step
Evaluation Metrics:
 -RMSE : 84.34
 -MAE  : 46.05
 -MAPE : 77.70%
 -R²   : 0.5022

--- Processing target 4 out of 19: CYC_North Strand Rd N B

Training model for: CYC_North Strand Rd N B
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 151ms/step - loss: 0.0280 - mae: 0.0548 - val_loss: 0.0199 - val_mae: 0.0843
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 124ms/step - loss: 0.0169 - mae: 0.0400 - val_loss: 0.0120 - val_mae: 0.0591
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 121ms/step - loss: 0.0108 - mae: 0.0359 - val_loss: 0.0062 - val_mae: 0.0011
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0074 - mae: 0.0342 - val_loss: 0.0042 - val_mae: 0.0139
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0053 - mae: 0.0326 - val_loss: 0.0046 - val_mae: 0.0574
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0040 - mae: 0.0316 - val_loss: 0.0065 - val_mae: 0.0910
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0033 - mae: 0.0310 - val_loss: 0.0044 - val_mae: 0.0720
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0027 - mae: 0.0288 - val_loss: 0.0094 - val_mae: 0.1026
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0023 - mae: 0.0273 - val_loss: 9.4045e-04 - val_mae: 5.2387e-06
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0020 - mae: 0.0260 - val_loss: 7.8373e-04 - val_mae: 1.6163e-04
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0018 - mae: 0.0256 - val_loss: 0.0822 - val_mae: 0.3835
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0017 - mae: 0.0250 - val_loss: 0.0302 - val_mae: 0.1866
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0016 - mae: 0.0247 - val_loss: 0.0052 - val_mae: 0.0379
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0015 - mae: 0.0245 - val_loss: 0.0334 - val_mae: 0.1840
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0015 - mae: 0.0244 - val_loss: 4.3227e-04 - val_mae: 0.0000e+00
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0015 - mae: 0.0245 - val_loss: 4.1296e-04 - val_mae: 0.0000e+00
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0014 - mae: 0.0242 - val_loss: 3.9102e-04 - val_mae: 0.0000e+00
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0014 - mae: 0.0239 - val_loss: 3.6727e-04 - val_mae: 0.0000e+00
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0013 - mae: 0.0237 - val_loss: 0.0065 - val_mae: 0.1055
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 124ms/step - loss: 0.0014 - mae: 0.0243 - val_loss: 3.4476e-04 - val_mae: 0.0000e+00
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 121ms/step - loss: 0.0014 - mae: 0.0243 - val_loss: 0.0025 - val_mae: 0.0257
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0012 - mae: 0.0231 - val_loss: 6.1939e-04 - val_mae: 0.0043
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0013 - mae: 0.0237 - val_loss: 3.0256e-04 - val_mae: 0.0000e+00
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0013 - mae: 0.0235 - val_loss: 2.8939e-04 - val_mae: 0.0000e+00
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0012 - mae: 0.0235 - val_loss: 2.8885e-04 - val_mae: 0.0000e+00
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0012 - mae: 0.0236 - val_loss: 2.8651e-04 - val_mae: 0.0000e+00
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0012 - mae: 0.0232 - val_loss: 2.7859e-04 - val_mae: 0.0000e+00
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0012 - mae: 0.0237 - val_loss: 0.0011 - val_mae: 0.0086
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0012 - mae: 0.0233 - val_loss: 0.0010 - val_mae: 0.0121
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0011 - mae: 0.0225 - val_loss: 2.6597e-04 - val_mae: 1.8440e-06
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0012 - mae: 0.0233 - val_loss: 4.5168e-04 - val_mae: 0.0047
Epoch 32/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0012 - mae: 0.0226 - val_loss: 7.4104e-04 - val_mae: 0.0098
Epoch 33/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 121ms/step - loss: 0.0012 - mae: 0.0225 - val_loss: 3.5661e-04 - val_mae: 0.0050
Epoch 34/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0012 - mae: 0.0235 - val_loss: 2.5430e-04 - val_mae: 0.0000e+00
Epoch 35/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0012 - mae: 0.0225 - val_loss: 2.5281e-04 - val_mae: 7.9939e-04
Epoch 36/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0011 - mae: 0.0225 - val_loss: 0.0131 - val_mae: 0.0807
Epoch 37/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0011 - mae: 0.0227 - val_loss: 0.0064 - val_mae: 0.0422
Epoch 38/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 121ms/step - loss: 0.0011 - mae: 0.0224 - val_loss: 0.0064 - val_mae: 0.0778
Epoch 39/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0011 - mae: 0.0222 - val_loss: 0.0014 - val_mae: 0.0227
Epoch 40/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0011 - mae: 0.0227 - val_loss: 2.4477e-04 - val_mae: 0.0000e+00
Epoch 41/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0012 - mae: 0.0227 - val_loss: 2.4646e-04 - val_mae: 0.0000e+00
Epoch 42/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0011 - mae: 0.0221 - val_loss: 2.3869e-04 - val_mae: 0.0000e+00
Epoch 43/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0011 - mae: 0.0229 - val_loss: 2.4624e-04 - val_mae: 0.0000e+00
Epoch 44/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0011 - mae: 0.0226 - val_loss: 2.4797e-04 - val_mae: 0.0000e+00
Epoch 45/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 121ms/step - loss: 0.0011 - mae: 0.0221 - val_loss: 0.0074 - val_mae: 0.0657
Epoch 46/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0010 - mae: 0.0215 - val_loss: 2.3530e-04 - val_mae: 0.0000e+00
Epoch 47/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0011 - mae: 0.0224 - val_loss: 2.3619e-04 - val_mae: 0.0000e+00
Epoch 48/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0011 - mae: 0.0219 - val_loss: 7.4335e-04 - val_mae: 0.0095
Epoch 49/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0011 - mae: 0.0218 - val_loss: 2.2786e-04 - val_mae: 0.0000e+00
Epoch 50/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0011 - mae: 0.0223 - val_loss: 2.2305e-04 - val_mae: 2.8308e-06
Epoch 51/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0011 - mae: 0.0219 - val_loss: 2.4844e-04 - val_mae: 0.0010
Epoch 52/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 121ms/step - loss: 0.0012 - mae: 0.0235 - val_loss: 2.2936e-04 - val_mae: 0.0000e+00
Epoch 53/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0012 - mae: 0.0229 - val_loss: 2.3078e-04 - val_mae: 0.0000e+00
Epoch 54/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0011 - mae: 0.0216 - val_loss: 2.2491e-04 - val_mae: 3.5848e-05
Epoch 55/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0011 - mae: 0.0226 - val_loss: 2.2847e-04 - val_mae: 0.0000e+00
------Training completed for: CYC_North Strand Rd N B

----- Evaluating model for: CYC_North Strand Rd N B (5/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step
Evaluation Metrics:
 -RMSE : 0.00
 -MAE  : 0.00
 -MAPE : nan%
 -R²   : 1.0000

--- Processing target 5 out of 19: CYC_Richmond Street Cyclists 1 Merged

Training model for: CYC_Richmond Street Cyclists 1 Merged
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 150ms/step - loss: 0.0330 - mae: 0.0808 - val_loss: 0.0355 - val_mae: 0.1610
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0202 - mae: 0.0491 - val_loss: 0.0209 - val_mae: 0.0922
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0140 - mae: 0.0417 - val_loss: 0.0317 - val_mae: 0.1643
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0100 - mae: 0.0363 - val_loss: 0.0293 - val_mae: 0.1643
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0076 - mae: 0.0339 - val_loss: 0.0252 - val_mae: 0.1525
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0060 - mae: 0.0316 - val_loss: 0.0131 - val_mae: 0.0925
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0049 - mae: 0.0301 - val_loss: 0.0094 - val_mae: 0.0797
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0041 - mae: 0.0288 - val_loss: 0.0112 - val_mae: 0.1108
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0035 - mae: 0.0280 - val_loss: 0.0090 - val_mae: 0.0745
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0031 - mae: 0.0278 - val_loss: 0.0088 - val_mae: 0.0687
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0028 - mae: 0.0269 - val_loss: 0.0103 - val_mae: 0.0782
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0025 - mae: 0.0266 - val_loss: 0.0231 - val_mae: 0.1853
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0023 - mae: 0.0264 - val_loss: 0.0276 - val_mae: 0.2167
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0022 - mae: 0.0261 - val_loss: 0.0197 - val_mae: 0.1812
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0020 - mae: 0.0257 - val_loss: 0.0227 - val_mae: 0.1895
------Training completed for: CYC_Richmond Street Cyclists 1 Merged

----- Evaluating model for: CYC_Richmond Street Cyclists 1 Merged (6/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step
Evaluation Metrics:
 -RMSE : 40.11
 -MAE  : 24.19
 -MAPE : 109.88%
 -R²   : 0.2449

--- Processing target 6 out of 19: CYC_Richmond Street Cyclists 2 Merged

Training model for: CYC_Richmond Street Cyclists 2 Merged
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 151ms/step - loss: 0.0346 - mae: 0.0963 - val_loss: 0.0377 - val_mae: 0.1421
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0210 - mae: 0.0554 - val_loss: 0.0318 - val_mae: 0.1421
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0143 - mae: 0.0423 - val_loss: 0.0281 - val_mae: 0.1421
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0103 - mae: 0.0354 - val_loss: 0.0257 - val_mae: 0.1421
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0078 - mae: 0.0329 - val_loss: 0.0237 - val_mae: 0.1411
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 124ms/step - loss: 0.0061 - mae: 0.0310 - val_loss: 0.0098 - val_mae: 0.0709
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0049 - mae: 0.0294 - val_loss: 0.0147 - val_mae: 0.1364
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0041 - mae: 0.0284 - val_loss: 0.0090 - val_mae: 0.0848
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0035 - mae: 0.0276 - val_loss: 0.0086 - val_mae: 0.0789
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0030 - mae: 0.0270 - val_loss: 0.0309 - val_mae: 0.2253
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0027 - mae: 0.0263 - val_loss: 0.0568 - val_mae: 0.3174
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0024 - mae: 0.0261 - val_loss: 0.0268 - val_mae: 0.1968
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0023 - mae: 0.0260 - val_loss: 0.0508 - val_mae: 0.2965
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0021 - mae: 0.0257 - val_loss: 0.0299 - val_mae: 0.2229
------Training completed for: CYC_Richmond Street Cyclists 2 Merged

----- Evaluating model for: CYC_Richmond Street Cyclists 2 Merged (7/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step
Evaluation Metrics:
 -RMSE : 36.24
 -MAE  : 25.14
 -MAPE : 247.59%
 -R²   : 0.2743

--- Processing target 7 out of 19: FTF_Aston Quay Merged

Training model for: FTF_Aston Quay Merged
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 153ms/step - loss: 0.0296 - mae: 0.0661 - val_loss: 0.0290 - val_mae: 0.1246
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0185 - mae: 0.0584 - val_loss: 0.0227 - val_mae: 0.1301
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 124ms/step - loss: 0.0117 - mae: 0.0457 - val_loss: 0.0255 - val_mae: 0.1611
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0082 - mae: 0.0423 - val_loss: 0.0244 - val_mae: 0.1663
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 121ms/step - loss: 0.0059 - mae: 0.0387 - val_loss: 0.0240 - val_mae: 0.1703
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 123ms/step - loss: 0.0047 - mae: 0.0376 - val_loss: 0.0233 - val_mae: 0.1712
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0038 - mae: 0.0358 - val_loss: 0.0270 - val_mae: 0.1903
------Training completed for: FTF_Aston Quay Merged

----- Evaluating model for: FTF_Aston Quay Merged (8/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step
Evaluation Metrics:
 -RMSE : 1185.88
 -MAE  : 950.87
 -MAPE : 226.12%
 -R²   : 0.0906

--- Processing target 8 out of 19: FTF_Capel St Mary St Merged

Training model for: FTF_Capel St Mary St Merged
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 148ms/step - loss: 0.0306 - mae: 0.0735 - val_loss: 0.0284 - val_mae: 0.1119
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0184 - mae: 0.0479 - val_loss: 0.0223 - val_mae: 0.1119
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0124 - mae: 0.0431 - val_loss: 0.0185 - val_mae: 0.1119
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0088 - mae: 0.0400 - val_loss: 0.0121 - val_mae: 0.0832
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 124ms/step - loss: 0.0066 - mae: 0.0384 - val_loss: 0.0072 - val_mae: 0.0696
Epoch 6/100

## **3.6 MODEL SUMMARY**

In [ ]:
for target_name, model in models.items():
    print(f"\n---Summary for target: {target_name}")
    model.summary()

---Summary for target: CYC_Clontarf James Larkin Rd

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: CYC_Clontarf Pebble Beach Carpark

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: CYC_Grove Road Totem

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)               │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_5 (Conv1D)               │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_12 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_13 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_14 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: CYC_North Strand Rd N B

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_6 (Conv1D)               │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_15 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_7 (Conv1D)               │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_16 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_17 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_18 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_19 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: CYC_Richmond Street Cyclists 1 Merged

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_8 (Conv1D)               │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_8           │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_9 (Conv1D)               │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_9           │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_21 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_22 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_9 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_23 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_24 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: CYC_Richmond Street Cyclists 2 Merged

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_10 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_10          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_25 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_11 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_11          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_26 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_10 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_27 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_11 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_28 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_29 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Aston Quay Merged

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_12          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_30 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_13 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_13          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_31 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_12 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_32 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_13 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_33 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_34 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Capel St Mary St Merged

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_14 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_14          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_35 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_15 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_15          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_36 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_14 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_37 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_15 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_38 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_39 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_College St Dame St Merged

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_16 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_16          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_40 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_17 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_17          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_41 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_16 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_42 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_17 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_43 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_44 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Dame St Merged

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_18 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_18          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_45 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_19 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_19          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_46 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_18 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_47 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_19 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_48 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_49 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Dolier St Burgh Quay Merged

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_20 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_20          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_50 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_21 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_21          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_51 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_20 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_52 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_21 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_53 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_54 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Grafton St Monsoon Merged

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_22 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_22          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_55 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_23 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_23          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_56 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_22 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_57 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_23 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_58 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_59 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Grafton St Nassau St Suffolk St

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_24 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_24          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_60 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_25 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_25          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_61 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_24 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_62 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_25 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_63 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_64 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Henry St Merged

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_26 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_26          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_65 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_27 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_27          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_66 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_26 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_67 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_27 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_68 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_69 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_27 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Mary St Merged

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_28 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_28          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_70 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_29 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_29          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_71 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_28 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_72 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_29 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_73 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_74 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Oconnell St Princes St North Merged

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_30 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_30          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_75 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_31 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_31          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_76 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_30 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_77 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_31 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_78 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_30 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_79 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Talbot St Guineys Merged

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_32 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_32          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_80 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_33 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_33          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_81 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_32 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_82 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_33 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_83 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_84 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Westmoreland St East Fleet St Merged

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_34 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_34          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_85 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_35 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_35          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_86 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_34 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_87 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_35 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_88 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_89 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

---Summary for target: FTF_Westmoreland St West Merged

Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_36 (Conv1D)              │ (None, 24, 64)         │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_36          │ (None, 24, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_90 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_37 (Conv1D)              │ (None, 24, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_37          │ (None, 24, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_91 (Dropout)            │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_36 (LSTM)                  │ (None, 24, 64)         │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_92 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_37 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_93 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_94 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_37 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165,033 (644.67 KB)

 Trainable params: 54,945 (214.63 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 109,896 (429.29 KB)

## **3.7 RESULTS**

In [ ]:
results = pd.DataFrame.from_dict(results, orient="index")
results.index.name = "Target"
results = results.reset_index()
print("\nSummary of results CNN-LSTM tunned with coordinates:")
results

Summary of results CNN-LSTM tunned with coordinates:

,Target,RMSE,MAE,MAPE,R2
0,CYC_Clontarf James Larkin Rd,55.647083,50.286517,1126.305334,-1.093572
1,CYC_Clontarf Pebble Beach Carpark,29.964900,18.657303,64.676267,0.701203
2,CYC_Grove Road Totem,84.338870,46.045318,77.697737,0.502168
3,CYC_North Strand Rd N B,0.000000,0.000000,NaN,1.000000
4,CYC_Richmond Street Cyclists 1 Merged,40.114191,24.192260,109.876660,0.244941
5,CYC_Richmond Street Cyclists 2 Merged,36.243203,25.135830,247.594527,0.274258
6,FTF_Aston Quay Merged,1185.883175,950.874782,226.117283,0.090613
7,FTF_Capel St Mary St Merged,677.681752,576.506866,305.739785,-0.297645
8,FTF_College St Dame St Merged,241.366822,183.045693,186.603737,0.673437
9,FTF_Dame St Merged,538.112827,453.009363,481.329281,-1.837651
10,FTF_Dolier St Burgh Quay Merged,934.260756,896.805493,988.388194,-9.191380
11,FTF_Grafton St Monsoon Merged,1048.278081,909.532335,875.121470,0.090466
12,FTF_Grafton St Nassau St Suffolk St,158.512855,123.457928,379.854746,0.517758
13,FTF_Henry St Merged,4316.526231,3786.219725,11376.456995,-6.237301
14,FTF_Mary St Merged,868.997687,803.435206,1799.066209,-2.334564
15,FTF_Oconnell St Princes St North Merged,947.692221,878.820474,254.901594,-1.767333
16,FTF_Talbot St Guineys Merged,326.419408,115.048190,100.000000,-0.141845
17,FTF_Westmoreland St East Fleet St Merged,1180.379718,1156.985768,NaN,0.000000
18,FTF_Westmoreland St West Merged,485.246962,368.364045,187.443862,0.277277

### **3.8 PREDICTIONS**

In [ ]:
# Dictionary with DataFrames for all targets
predictions = {}

for target_name in targets:
    print(f"\nPredicting values for: {target_name}")
    X_test, y_test = test_sets[target_name]
    target_scaler = target_scaler_dict[target_name]

    # Scale and descale predictions
    y_pred_scaled = models[target_name].predict(X_test)
    y_pred = target_scaler.inverse_transform(y_pred_scaled)
    y_true = target_scaler.inverse_transform(y_test.reshape(-1, 1))

    # Index of start with date and time
    # Sequence length in LSTM sequences
    seq_len = sequence_length
    n_total = len(y_cnn_lstm_dict[target_name])
    n_train = int(n_total * 0.7)
    n_val = int(n_total * 0.15)
    start_test_idx = seq_len + n_train + n_val

    datest = data["date and time"].iloc[start_test_idx:].reset_index(drop=True)

    # DataFrame with only whole numbers and avoiding negative values
    predsDataFrame = pd.DataFrame({
        "date and time": datest,
        "Real": np.maximum(np.round(y_true).astype(int).reshape(-1), 0),
        "CNNLSTM_coords": np.maximum(np.round(y_pred).astype(int).reshape(-1), 0)
    })

    predictions[target_name] = predsDataFrame
    print(predsDataFrame.head())

# Merge all targets in a single DataFrame
allpreds = pd.concat(
    [dataframe.assign(Target=target) for target, dataframe in predictions.items()],
    ignore_index=True
)

Predicting values for: CYC_Clontarf James Larkin Rd
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00    20              47
1  2024-03-07 07:00:00    49              50
2  2024-03-07 08:00:00    70              54
3  2024-03-07 09:00:00    51              57
4  2024-03-07 10:00:00    31              59

Predicting values for: CYC_Clontarf Pebble Beach Carpark
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00    26              18
1  2024-03-07 07:00:00    75              37
2  2024-03-07 08:00:00   105              55
3  2024-03-07 09:00:00    75              65
4  2024-03-07 10:00:00    33              64

Predicting values for: CYC_Grove Road Totem
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00   125             124
1  2024-03-07 07:00:00   309             188
2  2024-03-07 08:00:00   607             226
3  2024-03-07 09:00:00   247             170
4  2024-03-07 10:00:00    94             115

Predicting values for: CYC_North Strand Rd N B
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00     0               0
1  2024-03-07 07:00:00     0               0
2  2024-03-07 08:00:00     0               0
3  2024-03-07 09:00:00     0               0
4  2024-03-07 10:00:00     0               0

Predicting values for: CYC_Richmond Street Cyclists 1 Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00    21              22
1  2024-03-07 07:00:00    88              28
2  2024-03-07 08:00:00   244              36
3  2024-03-07 09:00:00   135              43
4  2024-03-07 10:00:00    75              49

Predicting values for: CYC_Richmond Street Cyclists 2 Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00    12              39
1  2024-03-07 07:00:00    38              45
2  2024-03-07 08:00:00    53              51
3  2024-03-07 09:00:00    37              51
4  2024-03-07 10:00:00    19              49

Predicting values for: FTF_Aston Quay Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00  1524            1720
1  2024-03-07 07:00:00  2191            1749
2  2024-03-07 08:00:00  4623            1780
3  2024-03-07 09:00:00  3941            1809
4  2024-03-07 10:00:00  2430            1836

Predicting values for: FTF_Capel St Mary St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00   348             504
1  2024-03-07 07:00:00   305             558
2  2024-03-07 08:00:00  1026             672
3  2024-03-07 09:00:00  1098             851
4  2024-03-07 10:00:00  1721            1096

Predicting values for: FTF_College St Dame St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00   250             420
1  2024-03-07 07:00:00   533             618
2  2024-03-07 08:00:00  1243             796
3  2024-03-07 09:00:00   966             830
4  2024-03-07 10:00:00   809             836

Predicting values for: FTF_Dame St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00   293             590
1  2024-03-07 07:00:00   480             658
2  2024-03-07 08:00:00   663             713
3  2024-03-07 09:00:00   702             759
4  2024-03-07 10:00:00   596             794

Predicting values for: FTF_Dolier St Burgh Quay Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00   291            1008
1  2024-03-07 07:00:00   494            1022
2  2024-03-07 08:00:00   823            1036
3  2024-03-07 09:00:00   752            1048
4  2024-03-07 10:00:00   535            1055

Predicting values for: FTF_Grafton St Monsoon Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00  1867            1241
1  2024-03-07 07:00:00  1909            1308
2  2024-03-07 08:00:00  1718            1387
3  2024-03-07 09:00:00  2174            1465
4  2024-03-07 10:00:00  2111            1536

Predicting values for: FTF_Grafton St Nassau St Suffolk St
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00    76             210
1  2024-03-07 07:00:00   162             249
2  2024-03-07 08:00:00   469             291
3  2024-03-07 09:00:00   330             331
4  2024-03-07 10:00:00   273             368

Predicting values for: FTF_Henry St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00   458            2356
1  2024-03-07 07:00:00   925            2822
2  2024-03-07 08:00:00  2353            3382
3  2024-03-07 09:00:00  3062            3998
4  2024-03-07 10:00:00  4369            4560

Predicting values for: FTF_Mary St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00    59             586
1  2024-03-07 07:00:00    87             668
2  2024-03-07 08:00:00   286             757
3  2024-03-07 09:00:00   334             858
4  2024-03-07 10:00:00   918             961

Predicting values for: FTF_Oconnell St Princes St North Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00   366             686
1  2024-03-07 07:00:00   598             780
2  2024-03-07 08:00:00  1050             880
3  2024-03-07 09:00:00   760             970
4  2024-03-07 10:00:00   720            1053

Predicting values for: FTF_Talbot St Guineys Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00     0               0
1  2024-03-07 07:00:00     0               0
2  2024-03-07 08:00:00     0               0
3  2024-03-07 09:00:00     0               0
4  2024-03-07 10:00:00     0               0

Predicting values for: FTF_Westmoreland St East Fleet St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00     0             980
1  2024-03-07 07:00:00     0            1056
2  2024-03-07 08:00:00     0            1129
3  2024-03-07 09:00:00     0            1192
4  2024-03-07 10:00:00     0            1242

Predicting values for: FTF_Westmoreland St West Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_coords
0  2024-03-07 06:00:00   325             300
1  2024-03-07 07:00:00   594             439
2  2024-03-07 08:00:00   934             579
3  2024-03-07 09:00:00   833             701
4  2024-03-07 10:00:00   930             800

In [ ]:
allpreds.head(20)

          date and time  Real  CNNLSTM_coords                        Target
0   2024-03-07 06:00:00    20              47  CYC_Clontarf James Larkin Rd
1   2024-03-07 07:00:00    49              50  CYC_Clontarf James Larkin Rd
2   2024-03-07 08:00:00    70              54  CYC_Clontarf James Larkin Rd
3   2024-03-07 09:00:00    51              57  CYC_Clontarf James Larkin Rd
4   2024-03-07 10:00:00    31              59  CYC_Clontarf James Larkin Rd
5   2024-03-07 11:00:00    32              58  CYC_Clontarf James Larkin Rd
6   2024-03-07 12:00:00    36              57  CYC_Clontarf James Larkin Rd
7   2024-03-07 13:00:00    33              57  CYC_Clontarf James Larkin Rd
8   2024-03-07 14:00:00    23              58  CYC_Clontarf James Larkin Rd
9   2024-03-07 15:00:00    25              61  CYC_Clontarf James Larkin Rd
10  2024-03-07 16:00:00    39              63  CYC_Clontarf James Larkin Rd
11  2024-03-07 17:00:00    68              65  CYC_Clontarf James Larkin Rd
12  2024-03-07 18:00:00    62              66  CYC_Clontarf James Larkin Rd
13  2024-03-07 19:00:00    33              65  CYC_Clontarf James Larkin Rd
14  2024-03-07 20:00:00     8              62  CYC_Clontarf James Larkin Rd
15  2024-03-07 21:00:00     7              57  CYC_Clontarf James Larkin Rd
16  2024-03-07 22:00:00     6              52  CYC_Clontarf James Larkin Rd
17  2024-03-07 23:00:00     1              47  CYC_Clontarf James Larkin Rd
18  2024-03-08 00:00:00     4              42  CYC_Clontarf James Larkin Rd
19  2024-03-08 01:00:00     2              39  CYC_Clontarf James Larkin Rd

## **4. RESULTS TO AZURE BLOB STORAGE**

In [ ]:
def save_blob(data, filename):
    try:
        blob_name = f"{CONTAINER_NAME}/{filename}"
        csv_data = data.to_csv(index=False)
        with fs.open(blob_name, "w") as f:
            f.write(csv_data)
        print(f"Saved to {blob_name}")
    except Exception as e:
        print(f"Error saving data to blob storage: {str(e)}")
        return False

In [ ]:
# Results
CONTAINER_NAME = "results"

save_blob(results, "rcnnlstm_coords.csv")

Saved to results/rcnnlstm_coords.csv

In [ ]:
# Predictions
CONTAINER_NAME = "predictions"

save_blob(allpreds, "pred_cnnlstm_coords.csv")

Saved to predictions/pred_cnnlstm_coords.csv

In [ ]:
allpreds.shape

(152190, 4)