# **RESULTS FROM EACH MACHINE LEARNING MODEL**

# **1. LIBRARIES**

In [48]:
! pip install adlfs azure-storage-blob

Requirement already satisfied: adlfs in /usr/local/lib/python3.11/dist-packages (2024.12.0)
Requirement already satisfied: azure-storage-blob in /usr/local/lib/python3.11/dist-packages (12.26.0)
Requirement already satisfied: azure-core<2.0.0,>=1.28.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (1.35.0)
Requirement already satisfied: azure-datalake-store<0.1,>=0.0.53 in /usr/local/lib/python3.11/dist-packages (from adlfs) (0.0.53)
Requirement already satisfied: azure-identity in /usr/local/lib/python3.11/dist-packages (from adlfs) (1.24.0)
Requirement already satisfied: fsspec>=2023.12.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (2025.3.0)
Requirement already satisfied: aiohttp>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (3.12.15)
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (43.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (4.14.1)
Requirement already satisfied: isodate>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (0.7.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.20.1)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (2.32.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (1.17.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.17.1)
Requirement already satisfied: msal<2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.33.0)
Requirement already satisfied: msal-extensions>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from azure-identity->adlfs) (1.3.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.22)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from PyJWT[crypto]<3,>=1.0.0->msal<2,>=1.16.0->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.10.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2025.8.3)

In [49]:
# STANDARD LIBRARY
import os
import io

# DATA MANIPULATION AND ANALYSIS
import pandas as pd
import numpy as np

# AZURE CLOUD STORAGE
from adlfs import AzureBlobFileSystem
from azure.storage.blob import BlobServiceClient

# **2. LOADING DATASETS FROM AZURE BLOB STORAGE**

In [50]:
def load_csv_from_blob(blob_name):
    blob_client = container_client.get_blob_client(blob_name)
    stream = blob_client.download_blob()
    data_bytes = stream.readall()
    data_str = data_bytes.decode("utf-8")
    return pd.read_csv(io.StringIO(data_str))


# Connection configuration
AZURE_STORAGE_ACCOUNT = "researchprojectx24104515"
AZURE_STORAGE_KEY = "bxpexO6i+Hz6n1WiipTn+sTCuLPGMS1BogMERrIrHd16DpQ0GLfQ0R33yrSw4MxsDomq5yNMgw1o+AStlx/MjA=="
connection_string = f"DefaultEndpointsProtocol=https;AccountName={AZURE_STORAGE_ACCOUNT};AccountKey={AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net"
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

fs = AzureBlobFileSystem(
    account_name=AZURE_STORAGE_ACCOUNT,
    account_key=AZURE_STORAGE_KEY
)

## **2.1 BASELINE (RANDOM FOREST AND XGBOOST)**

In [51]:
# Establish connection to counters dataset
CONTAINER_NAME = "results"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "rbaseline.csv"
baseline = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {baseline.shape}")

Loaded 'rbaseline.csv' with shape: (19, 9)

## **2.2 LSTM WITHOUT GEOGRAPHICAL COORDINATES**

In [52]:
# Establish connection to dataset
CONTAINER_NAME = "results"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "rlstm_nocoords.csv"
lstm_nocoords = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {lstm_nocoords.shape}")

Loaded 'rlstm_nocoords.csv' with shape: (19, 5)

## **2.3 LSTM WITH GEOGRAPHICAL COORDINATES**

In [53]:
# Establish connection to dataset
CONTAINER_NAME = "results"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "rlstm_coords.csv"
lstm_coords = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {lstm_coords.shape}")

Loaded 'rlstm_coords.csv' with shape: (19, 5)

## **2.4 CNN-LSTM WITHOUT GEOGRAPHICAL COORDINATES**

In [54]:
# Establish connection to counters dataset
CONTAINER_NAME = "results"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "rcnnlstm_nocoords.csv"
cnnlstm_nocoords = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {cnnlstm_nocoords.shape}")

Loaded 'rcnnlstm_nocoords.csv' with shape: (19, 5)

## **2.5 CNN-LSTM WITH GEOGRAPHICAL COORDINATES**

In [55]:
# CNN-LSTM
# Establish connection to dataset
CONTAINER_NAME = "results"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "rcnnlstm_coords.csv"
cnnlstm_coords = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {cnnlstm_coords.shape}")

Loaded 'rcnnlstm_coords.csv' with shape: (19, 5)

# **3. NORMALISATION OF NAMES OF METRICS PER MODEL**

### **3.1 BASELINE (RANDOM FOREST AND XGBOOST)**

In [56]:
baseline = baseline.rename(columns={
    "MAE_mean_RF": "MAE_RF",
    "MAE_mean_XGB": "MAE_XGB",
    "MAPE_mean_RF": "MAPE_RF",
    "MAPE_mean_XGB": "MAPE_XGB",
    "R2_mean_RF": "R2_RF",
    "R2_mean_XGB": "R2_XGB",
    "RMSE_mean_RF": "RMSE_RF",
    "RMSE_mean_XGB": "RMSE_XGB"
})
baseline.head()

,Target,MAE_RF,MAE_XGB,MAPE_RF,MAPE_XGB,R2_RF,R2_XGB,RMSE_RF,RMSE_XGB
0,FTF_Aston Quay Merged,1265.240656,1122.844474,5.161247e+19,1.850703e+19,-0.924090,-0.582382,1644.274630,1531.527292
1,FTF_Capel St Mary St Merged,614.780301,587.305144,8.430593e+18,6.977373e+18,-0.519282,-0.385436,867.289999,867.872292
2,FTF_College St Dame St Merged,252.481402,249.661680,2.233591e+18,2.160484e+18,-0.243454,-0.226177,356.292232,340.495357
3,FTF_Dame St Merged,480.867790,467.376280,5.067617e+19,5.385044e+19,-1.616189,-1.522613,643.333287,625.665359
4,FTF_Dolier St Burgh Quay Merged,409.477808,428.559389,4.954735e+19,4.717178e+19,-0.631596,-0.689110,527.185026,551.477104

### **3.2 LSTM WITHOUT GEOGRAPHICAL COORDINATES**

In [57]:
lstm_nocoords = lstm_nocoords.rename(columns={
    "RMSE": "RMSE_lstm_nocrds",
    "MAE": "MAE_lstm_nocrds",
    "MAPE": "MAPE_lstm_nocrds",
    "R2": "R2_lstm_nocrds"
})
lstm_nocoords.head()

,Target,RMSE_lstm_nocrds,MAE_lstm_nocrds,MAPE_lstm_nocrds,R2_lstm_nocrds
0,CYC_Clontarf James Larkin Rd,20.205270,12.467665,60.847362,0.723985
1,CYC_Clontarf Pebble Beach Carpark,25.795065,16.428589,75.494677,0.778577
2,CYC_Grove Road Totem,118.567539,90.920974,392.726553,0.016082
3,CYC_North Strand Rd N B,1.179888,0.918477,NaN,0.000000
4,CYC_Richmond Street Cyclists 1 Merged,40.126031,24.078402,81.163775,0.244495

### **3.3 LSTM WITH GEOGRAPHICAL COORDINATES**

In [58]:
lstm_coords = lstm_coords.rename(columns={
    "RMSE": "RMSE_lstm_coords",
    "MAE": "MAE_lstm_coords",
    "MAPE": "MAPE_lstm_coords",
    "R2": "R2_lstm_coords"
})
lstm_coords.head()

,Target,RMSE_lstm_coords,MAE_lstm_coords,MAPE_lstm_coords,R2_lstm_coords
0,CYC_Clontarf James Larkin Rd,28.038978,21.949563,380.815510,0.468470
1,CYC_Clontarf Pebble Beach Carpark,74.996888,63.048315,657.111993,-0.871702
2,CYC_Grove Road Totem,74.741013,41.915356,144.178066,0.609028
3,CYC_North Strand Rd N B,5.043085,4.923346,NaN,0.000000
4,CYC_Richmond Street Cyclists 1 Merged,46.533369,35.262047,264.490548,-0.016047

### **3.4 CNN-LSTM WITHOUT GEOGRAPHICAL COORDINATES**

In [59]:
cnnlstm_nocoords = cnnlstm_nocoords.rename(columns={
    "RMSE": "RMSE_cnnlstm_nocrds",
    "MAE": "MAE_cnnlstm_nocrds",
    "MAPE": "MAPE_cnnlstm_nocrds",
    "R2": "R2_cnnlstm_nocrds"
})

cnnlstm_nocoords.head()

,Target,RMSE_cnnlstm_nocrds,MAE_cnnlstm_nocrds,MAPE_cnnlstm_nocrds,R2_cnnlstm_nocrds
0,CYC_Clontarf James Larkin Rd,18.883928,11.722347,62.211089,0.758905
1,CYC_Clontarf Pebble Beach Carpark,27.761920,17.818102,88.261566,0.743523
2,CYC_Grove Road Totem,41.386365,22.434457,47.366530,0.880121
3,CYC_North Strand Rd N B,0.000000,0.000000,NaN,1.000000
4,CYC_Richmond Street Cyclists 1 Merged,39.551493,24.278152,137.393276,0.265976

### **3.5 CNN-LSTM WITH GEOGRAPHICAL COORDINATES**

In [60]:
cnnlstm_coords = cnnlstm_coords.rename(columns={
    "RMSE": "RMSE_cnnlstm_coords",
    "MAE": "MAE_cnnlstm_coords",
    "MAPE": "MAPE_cnnlstm_coords",
    "R2": "R2_cnnlstm_coords"
})

cnnlstm_coords.head()

,Target,RMSE_cnnlstm_coords,MAE_cnnlstm_coords,MAPE_cnnlstm_coords,R2_cnnlstm_coords
0,CYC_Clontarf James Larkin Rd,55.647083,50.286517,1126.305334,-1.093572
1,CYC_Clontarf Pebble Beach Carpark,29.964900,18.657303,64.676267,0.701203
2,CYC_Grove Road Totem,84.338870,46.045318,77.697737,0.502168
3,CYC_North Strand Rd N B,0.000000,0.000000,NaN,1.000000
4,CYC_Richmond Street Cyclists 1 Merged,40.114191,24.192260,109.876660,0.244941

### **3.6 CHECK INTEGRITY**

In [61]:
baseline = baseline.loc[:, ~baseline.columns.duplicated()]
lstm_coords = lstm_coords.loc[:, ~lstm_coords.columns.duplicated()]
lstm_nocoords = lstm_nocoords.loc[:, ~lstm_nocoords.columns.duplicated()]
cnnlstm_coords = cnnlstm_coords.loc[:, ~cnnlstm_coords.columns.duplicated()]
cnnlstm_nocoords = cnnlstm_nocoords.loc[:, ~cnnlstm_nocoords.columns.duplicated()]

In [62]:
baseline.head()

,Target,MAE_RF,MAE_XGB,MAPE_RF,MAPE_XGB,R2_RF,R2_XGB,RMSE_RF,RMSE_XGB
0,FTF_Aston Quay Merged,1265.240656,1122.844474,5.161247e+19,1.850703e+19,-0.924090,-0.582382,1644.274630,1531.527292
1,FTF_Capel St Mary St Merged,614.780301,587.305144,8.430593e+18,6.977373e+18,-0.519282,-0.385436,867.289999,867.872292
2,FTF_College St Dame St Merged,252.481402,249.661680,2.233591e+18,2.160484e+18,-0.243454,-0.226177,356.292232,340.495357
3,FTF_Dame St Merged,480.867790,467.376280,5.067617e+19,5.385044e+19,-1.616189,-1.522613,643.333287,625.665359
4,FTF_Dolier St Burgh Quay Merged,409.477808,428.559389,4.954735e+19,4.717178e+19,-0.631596,-0.689110,527.185026,551.477104

In [63]:
lstm_coords.head()

,Target,RMSE_lstm_coords,MAE_lstm_coords,MAPE_lstm_coords,R2_lstm_coords
0,CYC_Clontarf James Larkin Rd,28.038978,21.949563,380.815510,0.468470
1,CYC_Clontarf Pebble Beach Carpark,74.996888,63.048315,657.111993,-0.871702
2,CYC_Grove Road Totem,74.741013,41.915356,144.178066,0.609028
3,CYC_North Strand Rd N B,5.043085,4.923346,NaN,0.000000
4,CYC_Richmond Street Cyclists 1 Merged,46.533369,35.262047,264.490548,-0.016047

In [64]:
lstm_nocoords.head()

,Target,RMSE_lstm_nocrds,MAE_lstm_nocrds,MAPE_lstm_nocrds,R2_lstm_nocrds
0,CYC_Clontarf James Larkin Rd,20.205270,12.467665,60.847362,0.723985
1,CYC_Clontarf Pebble Beach Carpark,25.795065,16.428589,75.494677,0.778577
2,CYC_Grove Road Totem,118.567539,90.920974,392.726553,0.016082
3,CYC_North Strand Rd N B,1.179888,0.918477,NaN,0.000000
4,CYC_Richmond Street Cyclists 1 Merged,40.126031,24.078402,81.163775,0.244495

In [65]:
cnnlstm_coords.head()

,Target,RMSE_cnnlstm_coords,MAE_cnnlstm_coords,MAPE_cnnlstm_coords,R2_cnnlstm_coords
0,CYC_Clontarf James Larkin Rd,55.647083,50.286517,1126.305334,-1.093572
1,CYC_Clontarf Pebble Beach Carpark,29.964900,18.657303,64.676267,0.701203
2,CYC_Grove Road Totem,84.338870,46.045318,77.697737,0.502168
3,CYC_North Strand Rd N B,0.000000,0.000000,NaN,1.000000
4,CYC_Richmond Street Cyclists 1 Merged,40.114191,24.192260,109.876660,0.244941

In [66]:
cnnlstm_nocoords.head()

,Target,RMSE_cnnlstm_nocrds,MAE_cnnlstm_nocrds,MAPE_cnnlstm_nocrds,R2_cnnlstm_nocrds
0,CYC_Clontarf James Larkin Rd,18.883928,11.722347,62.211089,0.758905
1,CYC_Clontarf Pebble Beach Carpark,27.761920,17.818102,88.261566,0.743523
2,CYC_Grove Road Totem,41.386365,22.434457,47.366530,0.880121
3,CYC_North Strand Rd N B,0.000000,0.000000,NaN,1.000000
4,CYC_Richmond Street Cyclists 1 Merged,39.551493,24.278152,137.393276,0.265976

## **4. MERGE INTO DATAFRAMES PER EVALUATION METRIC**

In [67]:
# Process Target column
def preprocess_t(dataframe):
    if dataframe.index.name == "Target":
        dataframe = dataframe.reset_index()
    dataframe = dataframe.loc[:, ~dataframe.columns.duplicated()]
    return dataframe

baseline = preprocess_t(baseline)
lstm_coords = preprocess_t(lstm_coords)
lstm_nocoords = preprocess_t(lstm_nocoords)
cnnlstm_coords = preprocess_t(cnnlstm_coords)
cnnlstm_nocoords = preprocess_t(cnnlstm_nocoords)

metrics = ["MAE", "MAPE", "RMSE", "R2"]

# Filter columns by metric
def fbymetric(dataframe, metric):
    cols = ["Target"] + [col for col in dataframe.columns if metric in col]
    return dataframe[cols]

# Dictionary with all results
results = {}

for metric in metrics:
    merged = (
        fbymetric(baseline, metric)
        .merge(fbymetric(lstm_nocoords, metric), on="Target", how="inner", suffixes=("_baseline", "_lstm_nocrds"))
        .merge(fbymetric(lstm_coords, metric), on="Target", how="inner", suffixes=("", "_lstm_coords"))
        .merge(fbymetric(cnnlstm_nocoords, metric), on="Target", how="inner", suffixes=("", "_cnnlstm_nocrds"))
        .merge(fbymetric(cnnlstm_coords, metric), on="Target", how="inner", suffixes=("", "_cnnlstm_coords"))
    )
    results[metric] = merged

In [68]:
mae = results["MAE"]
mae

,Target,MAE_RF,MAE_XGB,MAE_lstm_nocrds,MAE_lstm_coords,MAE_cnnlstm_nocrds,MAE_cnnlstm_coords
0,FTF_Aston Quay Merged,1265.240656,1122.844474,2059.324844,3029.949439,1517.101124,950.874782
1,FTF_Capel St Mary St Merged,614.780301,587.305144,1751.740324,972.622097,916.473658,576.506866
2,FTF_College St Dame St Merged,252.481402,249.661680,283.922347,143.012360,181.217228,183.045693
3,FTF_Dame St Merged,480.867790,467.376280,232.082272,412.412609,349.499001,453.009363
4,FTF_Dolier St Burgh Quay Merged,409.477808,428.559389,1466.169288,970.124719,1114.013483,896.805493
5,FTF_Grafton St Monsoon Merged,1374.631806,1398.443037,561.138826,591.138952,1084.665793,909.532335
6,FTF_Grafton St Nassau St Suffolk St,142.898383,141.711523,102.356180,95.756180,83.795131,123.457928
7,FTF_Henry St Merged,1599.017453,1428.943980,6524.537078,5214.616728,4484.051685,3786.219725
8,FTF_Mary St Merged,305.229111,292.440791,177.556679,158.634832,147.590137,803.435206
9,FTF_Oconnell St Princes St North Merged,404.968351,401.957839,722.358801,575.675281,830.131461,878.820474
10,FTF_Talbot St Guineys Merged,1018.870328,949.355930,2383.543071,946.192634,1481.784395,115.048190
11,FTF_Westmoreland St East Fleet St Merged,493.436995,454.965993,1691.871411,1211.698127,1352.572160,1156.985768
12,FTF_Westmoreland St West Merged,563.214331,617.485984,252.518851,457.738452,334.627216,368.364045
13,CYC_Clontarf James Larkin Rd,18.066083,15.866757,12.467665,21.949563,11.722347,50.286517
14,CYC_Clontarf Pebble Beach Carpark,23.348787,20.648540,16.428589,63.048315,17.818102,18.657303
15,CYC_Grove Road Totem,32.657615,33.046586,90.920974,41.915356,22.434457,46.045318
16,CYC_North Strand Rd N B,17.627224,15.322597,0.918477,4.923346,0.000000,0.000000
17,CYC_Richmond Street Cyclists 1 Merged,14.468980,12.879582,24.078402,35.262047,24.278152,24.192260
18,CYC_Richmond Street Cyclists 2 Merged,15.282367,12.931020,15.119850,31.329713,14.982272,25.135830

In [69]:
mape = results["MAPE"]
mape

,Target,MAPE_RF,MAPE_XGB,MAPE_lstm_nocrds,MAPE_lstm_coords,MAPE_cnnlstm_nocrds,MAPE_cnnlstm_coords
0,FTF_Aston Quay Merged,5.161247e+19,1.850703e+19,414.334514,594.334387,172.005987,226.117283
1,FTF_Capel St Mary St Merged,8.430593e+18,6.977373e+18,972.582342,429.910520,418.042156,305.739785
2,FTF_College St Dame St Merged,2.233591e+18,2.160484e+18,233.610354,80.163863,61.174618,186.603737
3,FTF_Dame St Merged,5.067617e+19,5.385044e+19,270.478224,356.388842,390.951687,481.329281
4,FTF_Dolier St Burgh Quay Merged,4.954735e+19,4.717178e+19,1382.453900,947.664519,1005.723538,988.388194
5,FTF_Grafton St Monsoon Merged,1.974762e+20,2.295303e+20,253.269632,311.951197,754.174622,875.121470
6,FTF_Grafton St Nassau St Suffolk St,1.608277e+18,1.468394e+18,224.771504,172.689714,126.742626,379.854746
7,FTF_Henry St Merged,3.141191e+20,2.651844e+20,6161.614569,3547.774543,2594.943027,11376.456995
8,FTF_Mary St Merged,1.299550e+19,1.033384e+19,156.732111,200.730034,71.262975,1799.066209
9,FTF_Oconnell St Princes St North Merged,4.273380e+19,3.722403e+19,119.491006,62.100717,145.951899,254.901594
10,FTF_Talbot St Guineys Merged,1.234930e+20,1.054627e+20,6496.936866,2834.003631,4382.467417,100.000000
11,FTF_Westmoreland St East Fleet St Merged,9.371470e+19,8.948913e+19,NaN,NaN,NaN,NaN
12,FTF_Westmoreland St West Merged,7.106563e+19,8.324837e+19,120.044395,218.226043,184.974060,187.443862
13,CYC_Clontarf James Larkin Rd,6.750341e+16,6.994135e+16,60.847362,380.815510,62.211089,1126.305334
14,CYC_Clontarf Pebble Beach Carpark,6.358856e+16,6.684588e+16,75.494677,657.111993,88.261566,64.676267
15,CYC_Grove Road Totem,2.112200e+16,9.670802e+15,392.726553,144.178066,47.366530,77.697737
16,CYC_North Strand Rd N B,4.027839e+18,2.852219e+18,NaN,NaN,NaN,NaN
17,CYC_Richmond Street Cyclists 1 Merged,4.785328e+17,3.950361e+17,81.163775,264.490548,137.393276,109.876660
18,CYC_Richmond Street Cyclists 2 Merged,3.860228e+16,5.337150e+16,46.220968,248.341429,54.676945,247.594527

In [70]:
r2 = results["R2"]
r2

,Target,R2_RF,R2_XGB,R2_lstm_nocrds,R2_lstm_coords,R2_cnnlstm_nocrds,R2_cnnlstm_coords
0,FTF_Aston Quay Merged,-0.924090,-0.582382,-2.124199,-6.033072,-0.857670,0.090613
1,FTF_Capel St Mary St Merged,-0.519282,-0.385436,-8.417004,-2.713268,-2.162089,-0.297645
2,FTF_College St Dame St Merged,-0.243454,-0.226177,0.321135,0.738126,0.566426,0.673437
3,FTF_Dame St Merged,-1.616189,-1.522613,0.080669,-1.801352,-1.051619,-1.837651
4,FTF_Dolier St Burgh Quay Merged,-0.631596,-0.689110,-26.652592,-11.166138,-14.820458,-9.191380
5,FTF_Grafton St Monsoon Merged,-1.943777,-2.299100,0.574542,0.505918,-0.269759,0.090466
6,FTF_Grafton St Nassau St Suffolk St,-0.141786,-0.194927,0.621813,0.619997,0.692837,0.517758
7,FTF_Henry St Merged,-0.590119,-0.395294,-27.675846,-18.873644,-13.643491,-6.237301
8,FTF_Mary St Merged,-0.858673,-0.418481,0.712696,0.802970,0.770701,-2.334564
9,FTF_Oconnell St Princes St North Merged,-0.165479,-0.145923,-1.229043,-0.550241,-1.861287,-1.767333
10,FTF_Talbot St Guineys Merged,-6.516482,-4.399074,-63.495949,-9.508883,-23.581309,-0.141845
11,FTF_Westmoreland St East Fleet St Merged,-0.892349,-0.460703,0.000000,0.000000,0.000000,0.000000
12,FTF_Westmoreland St West Merged,-0.835615,-1.270808,0.605144,0.033047,0.453011,0.277277
13,CYC_Clontarf James Larkin Rd,0.416848,0.515749,0.723985,0.468470,0.758905,-1.093572
14,CYC_Clontarf Pebble Beach Carpark,0.450805,0.533209,0.778577,-0.871702,0.743523,0.701203
15,CYC_Grove Road Totem,0.603559,0.565359,0.016082,0.609028,0.880121,0.502168
16,CYC_North Strand Rd N B,0.363283,0.162600,0.000000,0.000000,1.000000,1.000000
17,CYC_Richmond Street Cyclists 1 Merged,0.471819,0.537144,0.244495,-0.016047,0.265976,0.244941
18,CYC_Richmond Street Cyclists 2 Merged,0.459689,0.538482,0.665332,0.227783,0.648328,0.274258

In [71]:
rmse = results["RMSE"]
rmse

,Target,RMSE_RF,RMSE_XGB,RMSE_lstm_nocrds,RMSE_lstm_coords,RMSE_cnnlstm_nocrds,RMSE_cnnlstm_coords
0,FTF_Aston Quay Merged,1644.274630,1531.527292,2198.047077,3297.920323,1694.930461,1185.883175
1,FTF_Capel St Mary St Merged,867.289999,867.872292,1825.593882,1146.372930,1057.876128,677.681752
2,FTF_College St Dame St Merged,356.292232,340.495357,348.005419,216.142719,278.115970,241.366822
3,FTF_Dame St Merged,643.333287,625.665359,306.287914,534.659940,457.553778,538.112827
4,FTF_Dolier St Burgh Quay Merged,527.185026,551.477104,1538.932464,1020.770207,1164.021850,934.260756
5,FTF_Grafton St Monsoon Merged,2070.363295,2060.964874,716.961121,772.620936,1238.590537,1048.278081
6,FTF_Grafton St Nassau St Suffolk St,203.337803,201.036642,140.373535,140.710156,126.507465,158.512855
7,FTF_Henry St Merged,2668.356487,2458.711440,8592.196098,7152.944119,6140.000184,4316.526231
8,FTF_Mary St Merged,541.321868,513.311963,255.076038,211.234611,227.876959,868.997687
9,FTF_Oconnell St Princes St North Merged,535.815274,529.006583,850.542180,709.310253,963.645609,947.692221
10,FTF_Talbot St Guineys Merged,1426.590677,1335.290888,2453.231715,990.263111,1514.519406,326.419408
11,FTF_Westmoreland St East Fleet St Merged,649.550282,610.536049,1744.316966,1250.065557,1404.430021,1180.379718
12,FTF_Westmoreland St West Merged,721.761623,792.091356,358.671070,561.279703,422.149267,485.246962
13,CYC_Clontarf James Larkin Rd,30.269196,26.977750,20.205270,28.038978,18.883928,55.647083
14,CYC_Clontarf Pebble Beach Carpark,39.631178,35.599037,25.795065,74.996888,27.761920,29.964900
15,CYC_Grove Road Totem,61.025415,60.953238,118.567539,74.741013,41.386365,84.338870
16,CYC_North Strand Rd N B,31.494229,29.303943,1.179888,5.043085,0.000000,0.000000
17,CYC_Richmond Street Cyclists 1 Merged,24.025472,21.479287,40.126031,46.533369,39.551493,40.114191
18,CYC_Richmond Street Cyclists 2 Merged,23.795203,20.793194,24.611752,37.385669,25.229261,36.243203

# **4. PREDICTIONS**

## **4.1 BASELINE (RANDOM FOREST AND XGBOOST)**

In [72]:
# Establish connection to counters dataset
CONTAINER_NAME = "predictions"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

# Random Forest
file_name = "pred_rf.csv"
pred_rf = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {pred_rf.shape}")

# XGboost
file_name = "pred_xgb.csv"
pred_xgb = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {pred_xgb.shape}")

Loaded 'pred_rf.csv' with shape: (1015056, 4)
Loaded 'pred_xgb.csv' with shape: (1015056, 4)

## **4.2 DEEP LEARNING MODELS (LSTM & CNN-LSTM)**

In [73]:
# Establish connection to counters dataset
CONTAINER_NAME = "predictions"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

# LSTM no coordinates
file_name = "pred_lstm_nocoords.csv"
pred_lstm_nocoords = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {pred_lstm_nocoords.shape}")

# LSTM with coordinates
file_name = "pred_lstm_coords.csv"
pred_lstm_coords = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {pred_lstm_coords.shape}")

# CNN-LSTM no coordinates
file_name = "pred_cnnlstm_nocoords.csv"
pred_cnnlstm_nocoords = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {pred_cnnlstm_nocoords.shape}")

# CNN-LSTM with coordinates
file_name = "pred_cnnlstm_coords.csv"
pred_cnnlstm_coords = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {pred_cnnlstm_coords.shape}")

Loaded 'pred_lstm_nocoords.csv' with shape: (152190, 4)
Loaded 'pred_lstm_coords.csv' with shape: (152190, 4)
Loaded 'pred_cnnlstm_nocoords.csv' with shape: (152190, 4)
Loaded 'pred_cnnlstm_coords.csv' with shape: (152190, 4)

In [74]:
pred_cnnlstm_nocoords.head()

         date and time  Real  CNNLSTM_nocoords                        Target
0  2024-03-07 06:00:00    20                23  CYC_Clontarf James Larkin Rd
1  2024-03-07 07:00:00    49                50  CYC_Clontarf James Larkin Rd
2  2024-03-07 08:00:00    70                67  CYC_Clontarf James Larkin Rd
3  2024-03-07 09:00:00    51                45  CYC_Clontarf James Larkin Rd
4  2024-03-07 10:00:00    31                41  CYC_Clontarf James Larkin Rd

In [75]:
pred_cnnlstm_coords.head()

         date and time  Real  CNNLSTM_coords                        Target
0  2024-03-07 06:00:00    20              47  CYC_Clontarf James Larkin Rd
1  2024-03-07 07:00:00    49              50  CYC_Clontarf James Larkin Rd
2  2024-03-07 08:00:00    70              54  CYC_Clontarf James Larkin Rd
3  2024-03-07 09:00:00    51              57  CYC_Clontarf James Larkin Rd
4  2024-03-07 10:00:00    31              59  CYC_Clontarf James Larkin Rd

## **4.3 MERGING ALL PREDICTIONS INTO A COMMON DATAFRAME**

In [76]:
# Consistency in datatypes
for dataframe in [pred_rf, pred_xgb, pred_lstm_nocoords, pred_lstm_coords, pred_cnnlstm_nocoords, pred_cnnlstm_coords]:
    dataframe["date and time"] = pd.to_datetime(dataframe["date and time"], errors="coerce")

# Merge all data using date and time and Target as join
allpreds = (
    pred_rf
    .merge(pred_xgb, on=["date and time", "Target", "Real"], how="inner")
    .merge(pred_lstm_nocoords, on=["date and time", "Target", "Real"], how="inner")
    .merge(pred_lstm_coords, on=["date and time", "Target", "Real"], how="inner")
    .merge(pred_cnnlstm_nocoords, on=["date and time", "Target", "Real"], how="inner")
    .merge(pred_cnnlstm_coords, on=["date and time", "Target", "Real"], how="inner")
)

/tmp/ipython-input-3634343238.py:9: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  .merge(pred_lstm_nocoords, on=["date and time", "Target", "Real"], how="inner")
/tmp/ipython-input-3634343238.py:10: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  .merge(pred_lstm_coords, on=["date and time", "Target", "Real"], how="inner")

In [77]:
print(f"Merged shape: {allpreds.shape}")
allpreds.head()

Merged shape: (145148, 9)

,date and time,Real,RF,Target,XGB,LSTM_nocoords,LSTM_coords,CNNLSTM_nocoords,CNNLSTM_coords
0,2024-03-07 06:00:00,20,15,CYC_Clontarf James Larkin Rd,20,25,25,23,47
1,2024-03-07 07:00:00,49,55,CYC_Clontarf James Larkin Rd,55,43,35,50,50
2,2024-03-07 08:00:00,70,55,CYC_Clontarf James Larkin Rd,75,52,43,67,54
3,2024-03-07 09:00:00,51,55,CYC_Clontarf James Larkin Rd,43,51,43,45,57
4,2024-03-07 10:00:00,31,55,CYC_Clontarf James Larkin Rd,40,43,38,41,59

In [78]:
print(allpreds.dtypes)

date and time       datetime64[ns]
Real                         int64
RF                           int64
Target                      object
XGB                          int64
LSTM_nocoords                int64
LSTM_coords                  int64
CNNLSTM_nocoords             int64
CNNLSTM_coords               int64
dtype: object

# **DATAFRAMES TO AZURE**

In [79]:
def save_blob(data, filename):
    try:
        blob_name = f"{CONTAINER_NAME}/{filename}"
        csv_data = data.to_csv(index=False)
        with fs.open(blob_name, "w") as f:
            f.write(csv_data)
        print(f"Saved to {blob_name}")
    except Exception as e:
        print(f"Error saving data to blob storage: {str(e)}")
        return False

In [80]:
CONTAINER_NAME = "visualisation"

save_blob(mae, "m_mae.csv")
save_blob(mape, "m_mape.csv")
save_blob(r2, "m_r2.csv")
save_blob(rmse, "m_rmse.csv")

Saved to visualisation/m_mae.csv
Saved to visualisation/m_mape.csv
Saved to visualisation/m_r2.csv
Saved to visualisation/m_rmse.csv

In [81]:
CONTAINER_NAME = "visualisation"

save_blob(allpreds, "all_preds.csv")

Saved to visualisation/all_preds.csv

In [82]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

In [83]:
!uname -a

Linux 98bb0232a69a 6.1.123+ #1 SMP PREEMPT_DYNAMIC Sun Mar 30 16:01:29 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

In [84]:
import psutil

ram_gb = psutil.virtual_memory().total / (1024**3)
print(f"RAM total disponible: {ram_gb:.2f} GB")

RAM total disponible: 12.67 GB

In [85]:
!pip install adlfs

Requirement already satisfied: adlfs in /usr/local/lib/python3.11/dist-packages (2024.12.0)
Requirement already satisfied: azure-core<2.0.0,>=1.28.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (1.35.0)
Requirement already satisfied: azure-datalake-store<0.1,>=0.0.53 in /usr/local/lib/python3.11/dist-packages (from adlfs) (0.0.53)
Requirement already satisfied: azure-identity in /usr/local/lib/python3.11/dist-packages (from adlfs) (1.24.0)
Requirement already satisfied: azure-storage-blob>=12.17.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (12.26.0)
Requirement already satisfied: fsspec>=2023.12.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (2025.3.0)
Requirement already satisfied: aiohttp>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (3.12.15)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.20.1)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (2.32.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (1.17.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (4.14.1)
Requirement already satisfied: cffi in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.17.1)
Requirement already satisfied: msal<2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.33.0)
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob>=12.17.0->adlfs) (43.0.3)
Requirement already satisfied: isodate>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob>=12.17.0->adlfs) (0.7.2)
Requirement already satisfied: msal-extensions>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from azure-identity->adlfs) (1.3.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.22)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from PyJWT[crypto]<3,>=1.0.0->msal<2,>=1.16.0->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.10.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2025.8.3)

In [86]:
!python --version

Python 3.11.13

In [87]:
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
import sklearn
import xgboost
import tensorflow as tf
import adlfs
import holidays
import tqdm
import re
print("pandas:", re.__version__)
print("numpy:", np.__version__)
print("matplotlib:", matplotlib.__version__)
print("seaborn:", sns.__version__)
print("scikit-learn:", sklearn.__version__)
print("xgboost:", xgboost.__version__)
print("tensorflow:", tf.__version__)
print("adlfs:", adlfs.__version__)
print("azure-storage-blob:", BlobServiceClient.__module__.split('.')[0] if BlobServiceClient else "No instalado")
print("holidays:", holidays.__version__ )

pandas: 2.2.1
numpy: 2.0.2
matplotlib: 3.10.0
seaborn: 0.13.2
scikit-learn: 1.6.1
xgboost: 3.0.3
tensorflow: 2.19.0
adlfs: 2024.12.0
azure-storage-blob: azure
holidays: 0.78